from __future__ import annotations

from pathlib import Path

from ai_ent.project_manifest import (
    compile_project_manifest,
    load_manifest_documents,
    resolve_capabilities,
    validate_project_manifest,
    write_capability_resolution,
    write_compiled_project,
)


def test_ai_ent_project_manifest_validates_cleanly() -> None:
    result = validate_project_manifest(Path("manifest/project/ai-ent"))

    assert result.ok
    assert result.requirements_count >= 20
    assert result.components_count >= 8
    assert result.interfaces_count >= 5
    assert len(result.capabilities_selected) == 20
    assert "C12" in result.already_satisfied
    assert "C15" in result.still_missing
    assert len(result.compilation_hash) == 64


def test_project_manifest_hash_is_deterministic() -> None:
    root = Path("manifest/project/ai-ent")
    first = validate_project_manifest(root)
    second = validate_project_manifest(root)

    assert first.compilation_hash == second.compilation_hash
    assert first.manifest_files == second.manifest_files


def test_manifest_validator_detects_unresolved_capability_reference(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    functional = target / "requirements" / "functional.yaml"
    functional.write_text(
        functional.read_text(encoding="utf-8").replace("capabilities: [C03, C20]", "capabilities: [C03, C99]"),
        encoding="utf-8",
    )

    result = validate_project_manifest(target)

    assert not result.ok
    assert any("unknown capability C99" in error for error in result.validation_errors)


def test_manifest_validator_detects_duplicate_ids(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    extra = target / "requirements" / "duplicate.yaml"
    extra.write_text(
        "requirements:\n"
        "  - id: FR-001\n"
        "    title: Duplicate\n"
        "    classification: NORMATIVE\n"
        "    source_refs: [R1]\n"
        "    capabilities: [C01]\n",
        encoding="utf-8",
    )

    result = validate_project_manifest(target)

    assert not result.ok
    assert any("duplicate id FR-001" in error for error in result.validation_errors)


def test_manifest_loader_finds_all_yaml_documents() -> None:
    documents = load_manifest_documents(Path("manifest/project/ai-ent"))

    assert Path("manifest/project/ai-ent/project.yaml") in documents
    assert Path("manifest/project/ai-ent/capabilities.yaml") in documents


def test_compile_project_manifest_is_repeatable() -> None:
    root = Path("manifest/project/ai-ent")
    first = compile_project_manifest(root)
    second = compile_project_manifest(root)

    assert first.lock.compiled_hash == second.lock.compiled_hash
    assert first.compiled_bytes == second.compiled_bytes
    assert first.lock.as_dict() == second.lock.as_dict()
    assert first.compiled.source_metadata["source_file_count"] == 30


def test_compiled_project_retains_source_provenance() -> None:
    compiled = compile_project_manifest(Path("manifest/project/ai-ent")).compiled

    assert compiled.capabilities[0]["source_manifest_file"] == "capabilities.yaml"
    assert compiled.requirements[0]["source_manifest_file"].startswith("requirements/")
    assert compiled.project["source_manifest_file"] == "project.yaml"


def test_compile_writes_generated_derivatives_without_secrets(tmp_path: Path) -> None:
    result = write_compiled_project(Path("manifest/project/ai-ent"), tmp_path / "compiled")

    project_json = tmp_path / "compiled" / "project.json"
    lock = tmp_path / "compiled" / "manifest.lock"
    first_project_bytes = project_json.read_bytes()
    first_lock_bytes = lock.read_bytes()
    result_again = write_compiled_project(Path("manifest/project/ai-ent"), tmp_path / "compiled")

    assert result.lock.compiled_hash == result_again.lock.compiled_hash
    assert project_json.read_bytes() == first_project_bytes
    assert lock.read_bytes() == first_lock_bytes
    assert "generated by ai_ent.project_manifest" in project_json.read_text(encoding="utf-8")
    assert "password" not in project_json.read_text(encoding="utf-8").lower()
    assert "secret" not in project_json.read_text(encoding="utf-8").lower()


def test_semantic_key_order_changes_preserve_compiled_hash(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    project = target / "project.yaml"
    project.write_text(
        "status: DEVELOPMENT\n"
        "classification: NORMATIVE\n"
        "version: 0.1.0\n"
        "name: AI-Enterprise\n"
        "id: PRJ-AI-ENT\n"
        "source_corpus:\n"
        + project.read_text(encoding="utf-8").split("source_corpus:\n", 1)[1],
        encoding="utf-8",
    )

    assert compile_project_manifest(source).lock.compiled_hash == compile_project_manifest(target).lock.compiled_hash


def test_material_requirement_change_changes_compiled_hash(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    functional = target / "requirements" / "functional.yaml"
    functional.write_text(
        functional.read_text(encoding="utf-8").replace("Parse approved project manifests", "Parse altered project manifests"),
        encoding="utf-8",
    )

    assert compile_project_manifest(source).lock.compiled_hash != compile_project_manifest(target).lock.compiled_hash


def test_material_capability_status_change_changes_compiled_hash(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    capabilities = target / "capabilities.yaml"
    capabilities.write_text(
        capabilities.read_text(encoding="utf-8").replace("status: REQUIRED", "status: DEFERRED", 1),
        encoding="utf-8",
    )

    assert compile_project_manifest(source).lock.compiled_hash != compile_project_manifest(target).lock.compiled_hash


def test_invalid_reference_blocks_compilation(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    interfaces = target / "architecture" / "interfaces.yaml"
    interfaces.write_text(
        interfaces.read_text(encoding="utf-8").replace("to_component: CMP-002", "to_component: CMP-999", 1),
        encoding="utf-8",
    )

    try:
        compile_project_manifest(target)
    except ValueError as exc:
        assert "validation failed" in str(exc)
    else:
        raise AssertionError("invalid reference did not block compilation")


def test_unknown_normative_field_changes_hash_without_being_dropped(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    operations = target / "operations.yaml"
    operations.write_text(
        operations.read_text(encoding="utf-8") + "unknown_normative_field: must remain visible\n",
        encoding="utf-8",
    )

    compiled = compile_project_manifest(target)

    assert compiled.lock.compiled_hash != compile_project_manifest(source).lock.compiled_hash
    assert compiled.compiled.as_dict()["operations"]


def test_capability_resolver_resolves_all_twenty_capabilities() -> None:
    resolution = resolve_capabilities(Path("manifest/project/ai-ent"))

    assert len(resolution.capabilities) == 20
    assert resolution.resolver_version == "mmc-003.1"
    assert len(resolution.source_compiled_hash) == 64
    assert len(resolution.capability_resolution_hash) == 64
    assert "C12" in resolution.satisfied_capabilities
    assert "C03" in resolution.partially_satisfied_capabilities
    assert "C01" in resolution.unsatisfied_capabilities


def test_capability_resolver_expands_direct_and_transitive_dependencies() -> None:
    resolution = resolve_capabilities(Path("manifest/project/ai-ent"))
    by_id = {capability.capability_id: capability for capability in resolution.capabilities}

    assert "C19" in by_id["C20"].direct_dependencies
    assert "C16" in by_id["C20"].transitive_dependencies
    assert ("C20", "C19") in resolution.direct_edges
    assert ("C20", "C01") in resolution.transitive_edges


def test_capability_conditional_dependency_false_is_not_applied() -> None:
    resolution = resolve_capabilities(Path("manifest/project/ai-ent"))
    by_id = {capability.capability_id: capability for capability in resolution.capabilities}

    assert by_id["C11"].conditional_dependencies_applied == ()
    assert "C06" not in by_id["C11"].direct_dependencies
    assert "C11" in resolution.deferred_capabilities


def test_capability_conditional_dependency_true_is_applied(tmp_path: Path) -> None:
    source = Path("manifest/project/ai-ent")
    target = tmp_path / "manifest"
    _copy_manifest(source, target)
    deployment = target / "deployment.yaml"
    deployment.write_text(
        deployment.read_text(encoding="utf-8").replace("current_mode: local_development", "current_mode: production_cloud"),
        encoding="utf-8",
    )

    resolution = resolve_capabilities(target)
    by_id = {capability.capability_id: capability for capability in resolution.capabilities}

    assert "C11" in resolution.conditional_capabilities_activated
    assert "C06" in by_id["C11"].direct_dependencies
    assert by_id["C11"].conditional_dependencies_applied


def test_capability_unknown_dependency_is_rejected(tmp_path: Path) -> None:
    target = tmp_path / "manifest"
    _copy_manifest(Path("manifest/project/ai-ent"), target)
    capabilities = target / "capabilities.yaml"
    capabilities.write_text(
        capabilities.read_text(encoding="utf-8").replace("depends_on: [C01]", "depends_on: [C99]", 1),
        encoding="utf-8",
    )

    try:
        resolve_capabilities(target)
    except ValueError as exc:
        assert "unknown capability C99" in str(exc)
    else:
        raise AssertionError("unknown capability dependency was not rejected")


def test_capability_self_dependency_is_rejected(tmp_path: Path) -> None:
    target = tmp_path / "manifest"
    _copy_manifest(Path("manifest/project/ai-ent"), target)
    capabilities = target / "capabilities.yaml"
    capabilities.write_text(
        capabilities.read_text(encoding="utf-8").replace("depends_on: [C01]", "depends_on: [C02]", 1),
        encoding="utf-8",
    )

    try:
        resolve_capabilities(target)
    except ValueError as exc:
        assert "C02 cannot depend on itself" in str(exc)
    else:
        raise AssertionError("self dependency was not rejected")


def test_capability_cycle_is_rejected(tmp_path: Path) -> None:
    target = tmp_path / "manifest"
    _copy_manifest(Path("manifest/project/ai-ent"), target)
    capabilities = target / "capabilities.yaml"
    capabilities.write_text(
        capabilities.read_text(encoding="utf-8").replace("depends_on: [C01]", "depends_on: [C01, C20]", 1),
        encoding="utf-8",
    )

    try:
        resolve_capabilities(target)
    except ValueError as exc:
        assert "capability dependency cycle" in str(exc)
    else:
        raise AssertionError("cycle was not rejected")


def test_capability_resolution_is_repeatable_and_writes_artifacts(tmp_path: Path) -> None:
    first = write_capability_resolution(Path("manifest/project/ai-ent"), tmp_path / "compiled-a")
    second = write_capability_resolution(Path("manifest/project/ai-ent"), tmp_path / "compiled-b")

    assert first.capability_resolution_hash == second.capability_resolution_hash
    assert (tmp_path / "compiled-a" / "capability-resolution.json").read_bytes() == (
        tmp_path / "compiled-b" / "capability-resolution.json"
    ).read_bytes()
    assert (tmp_path / "compiled-a" / "capability-graph.json").exists()
    assert (tmp_path / "compiled-a" / "capability-gaps.json").exists()


def test_material_capability_change_changes_resolution_hash(tmp_path: Path) -> None:
    target = tmp_path / "manifest"
    _copy_manifest(Path("manifest/project/ai-ent"), target)
    capabilities = target / "capabilities.yaml"
    capabilities.write_text(
        capabilities.read_text(encoding="utf-8").replace("maturity: VALIDATED", "maturity: NOT_IMPLEMENTED", 1),
        encoding="utf-8",
    )

    assert resolve_capabilities(Path("manifest/project/ai-ent")).capability_resolution_hash != resolve_capabilities(
        target
    ).capability_resolution_hash


def _copy_manifest(source: Path, target: Path) -> None:
    for path in source.rglob("*.yaml"):
        destination = target / path.relative_to(source)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
