from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from itertools import pairwise
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, ValidationError

Classification = Literal["NORMATIVE", "INFORMATIVE", "DECISION", "EXAMPLE", "FUTURE/DEFERRED"]
CapabilityStatus = Literal["REQUIRED", "CONDITIONAL", "DEFERRED", "NOT_REQUIRED"]
CapabilityMaturity = Literal["NOT_IMPLEMENTED", "DEVELOPMENT", "VALIDATED", "PRODUCTION_READY"]
DependencyType = Literal["REQUIRED", "CONDITIONAL", "OPTIONAL", "CONFLICTS_WITH"]
ResolvedCapabilityStatus = Literal["REQUIRED", "CONDITIONAL", "DEFERRED", "NOT_REQUIRED"]
CapabilitySatisfaction = Literal["SATISFIED", "PARTIALLY_SATISFIED", "UNSATISFIED", "DEFERRED", "NOT_APPLICABLE"]
TraceEdgeType = Literal[
    "REQUIRES_CAPABILITY",
    "IMPLEMENTED_BY_COMPONENT",
    "EXPOSED_BY_INTERFACE",
    "VERIFIED_BY",
    "JUSTIFIED_BY",
    "EVIDENCED_BY",
    "DEPENDS_ON",
]
TraceSeverity = Literal["ERROR", "WARNING", "INFO"]
RequirementCoverage = Literal["COVERED", "PARTIALLY_COVERED", "UNCOVERED", "DEFERRED", "BLOCKED", "INVALID"]
ArchitectureCoverage = Literal["JUSTIFIED", "PARTIALLY_JUSTIFIED", "ORPHANED", "DEFERRED"]
PlanFindingSeverity = Literal["ERROR", "WARNING", "INFO"]
WarningClassification = Literal["PLANNING_RELEVANT", "INFORMATIONAL", "REQUIRES_FUTURE_DECISION"]

PROJECT_MANIFEST_ROOT = Path("manifest/project/ai-ent")
PROJECT_MANIFEST_SCHEMA_VERSION = "ai-ent-project-manifest-v0.1"
PROJECT_MANIFEST_COMPILER_VERSION = "mmc-002.1"
CAPABILITY_RESOLVER_VERSION = "mmc-003.1"
TRACE_VALIDATOR_VERSION = "mmc-004.1"
IMPLEMENTATION_DAG_GENERATOR_VERSION = "mmc-005.1"
GENERATED_MARKER = "generated by ai_ent.project_manifest; source manifests remain authoritative"


class SourceRef(BaseModel):
    id: str
    path: str
    role: str


class ProjectDocument(BaseModel):
    id: str
    name: str
    version: str
    classification: Classification
    status: str
    source_corpus: list[SourceRef] = Field(default_factory=list)
    objectives: list[str] = Field(default_factory=list)
    already_implemented_platform_capabilities: list[str] = Field(default_factory=list)
    authority: dict[str, Any] = Field(default_factory=dict)


class Capability(BaseModel):
    id: str
    name: str
    status: CapabilityStatus
    maturity: CapabilityMaturity
    classification: Classification
    source_refs: list[str]
    depends_on: list[str] = Field(default_factory=list)
    conditional_dependencies: list[dict[str, Any]] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    evidence_refs: list[str] = Field(default_factory=list)


class TraceableItem(BaseModel):
    id: str
    title: str | None = None
    name: str | None = None
    classification: Classification | None = None
    source_refs: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    capability: str | None = None
    requirements: list[str] = Field(default_factory=list)
    epic: str | None = None
    depends_on: list[str] = Field(default_factory=list)
    from_component: str | None = None
    to_component: str | None = None


@dataclass(frozen=True)
class ManifestValidationResult:
    manifest_files: tuple[str, ...]
    requirements_count: int
    components_count: int
    interfaces_count: int
    capabilities_selected: tuple[str, ...]
    unresolved_decisions: tuple[str, ...]
    validation_errors: tuple[str, ...]
    validation_warnings: tuple[str, ...]
    already_satisfied: tuple[str, ...]
    still_missing: tuple[str, ...]
    compilation_hash: str

    @property
    def ok(self) -> bool:
        return not self.validation_errors

    def as_dict(self) -> dict[str, Any]:
        return {
            "manifest_files_loaded": list(self.manifest_files),
            "requirements_count": self.requirements_count,
            "components_count": self.components_count,
            "interfaces_count": self.interfaces_count,
            "capabilities_selected": list(self.capabilities_selected),
            "unresolved_decisions": list(self.unresolved_decisions),
            "validation_errors": list(self.validation_errors),
            "validation_warnings": list(self.validation_warnings),
            "implementation_areas_already_satisfied": list(self.already_satisfied),
            "implementation_areas_still_missing": list(self.still_missing),
            "compilation_hash": self.compilation_hash,
        }


@dataclass(frozen=True)
class CompiledProject:
    project: dict[str, Any]
    intake: dict[str, Any]
    requirements: tuple[dict[str, Any], ...]
    architecture: dict[str, Any]
    capabilities: tuple[dict[str, Any], ...]
    agents: tuple[dict[str, Any], ...]
    models: tuple[dict[str, Any], ...]
    tools: tuple[dict[str, Any], ...]
    verification: dict[str, Any]
    repository: dict[str, Any]
    deployment: dict[str, Any]
    operations: tuple[dict[str, Any], ...]
    planning: dict[str, Any]
    source_metadata: dict[str, Any]

    def as_dict(self) -> dict[str, Any]:
        return {
            "compiler_version": PROJECT_MANIFEST_COMPILER_VERSION,
            "manifest_schema_version": PROJECT_MANIFEST_SCHEMA_VERSION,
            "generated": GENERATED_MARKER,
            "source_authority": "manifest/project/ai-ent",
            "project": self.project,
            "intake": self.intake,
            "requirements": list(self.requirements),
            "architecture": self.architecture,
            "capabilities": list(self.capabilities),
            "agents": list(self.agents),
            "models": list(self.models),
            "tools": list(self.tools),
            "verification": self.verification,
            "repository": self.repository,
            "deployment": self.deployment,
            "operations": list(self.operations),
            "planning": self.planning,
            "source_metadata": self.source_metadata,
        }


@dataclass(frozen=True)
class ManifestLock:
    project_id: str
    manifest_schema_version: str
    compiler_version: str
    source_file_hashes: dict[str, str]
    source_compilation_hash: str
    compiled_hash: str
    generated: str = GENERATED_MARKER

    def as_dict(self) -> dict[str, Any]:
        return {
            "generated": self.generated,
            "project_id": self.project_id,
            "manifest_schema_version": self.manifest_schema_version,
            "compiler_version": self.compiler_version,
            "source_file_hashes": self.source_file_hashes,
            "source_compilation_hash": self.source_compilation_hash,
            "compiled_hash": self.compiled_hash,
        }


@dataclass(frozen=True)
class CompilationResult:
    compiled: CompiledProject
    lock: ManifestLock
    compiled_bytes: bytes
    validation: ManifestValidationResult


@dataclass(frozen=True)
class ResolvedCapability:
    capability_id: str
    name: str
    declared_status: CapabilityStatus
    resolved_status: ResolvedCapabilityStatus
    maturity: CapabilityMaturity
    satisfaction: CapabilitySatisfaction
    direct_dependencies: tuple[str, ...]
    transitive_dependencies: tuple[str, ...]
    conditional_dependencies_applied: tuple[dict[str, Any], ...]
    evidence_refs: tuple[str, ...]
    missing_requirements_components: tuple[str, ...]
    blockers: tuple[str, ...]
    source_provenance: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "capability_id": self.capability_id,
            "name": self.name,
            "declared_status": self.declared_status,
            "resolved_status": self.resolved_status,
            "maturity": self.maturity,
            "satisfaction": self.satisfaction,
            "direct_dependencies": list(self.direct_dependencies),
            "transitive_dependencies": list(self.transitive_dependencies),
            "conditional_dependencies_applied": list(self.conditional_dependencies_applied),
            "evidence_refs": list(self.evidence_refs),
            "missing_requirements_components": list(self.missing_requirements_components),
            "blockers": list(self.blockers),
            "source_provenance": list(self.source_provenance),
        }


@dataclass(frozen=True)
class CapabilityResolution:
    source_compiled_hash: str
    resolver_version: str
    capability_resolution_hash: str
    capabilities: tuple[ResolvedCapability, ...]
    direct_edges: tuple[tuple[str, str], ...]
    transitive_edges: tuple[tuple[str, str], ...]
    required_capabilities: tuple[str, ...]
    conditional_capabilities_activated: tuple[str, ...]
    deferred_capabilities: tuple[str, ...]
    satisfied_capabilities: tuple[str, ...]
    partially_satisfied_capabilities: tuple[str, ...]
    unsatisfied_capabilities: tuple[str, ...]
    blocked_capabilities: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": self.source_compiled_hash,
            "resolver_version": self.resolver_version,
            "capability_resolution_hash": self.capability_resolution_hash,
            "capabilities": [capability.as_dict() for capability in self.capabilities],
            "direct_edges": [list(edge) for edge in self.direct_edges],
            "transitive_edges": [list(edge) for edge in self.transitive_edges],
            "required_capabilities": list(self.required_capabilities),
            "conditional_capabilities_activated": list(self.conditional_capabilities_activated),
            "deferred_capabilities": list(self.deferred_capabilities),
            "satisfied_capabilities": list(self.satisfied_capabilities),
            "partially_satisfied_capabilities": list(self.partially_satisfied_capabilities),
            "unsatisfied_capabilities": list(self.unsatisfied_capabilities),
            "blocked_capabilities": list(self.blocked_capabilities),
        }


@dataclass(frozen=True)
class TraceEdge:
    source_id: str
    target_id: str
    edge_type: TraceEdgeType

    def as_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "target_id": self.target_id,
            "edge_type": self.edge_type,
        }


@dataclass(frozen=True)
class TracePath:
    requirement_id: str
    coverage: RequirementCoverage
    capabilities: tuple[str, ...]
    components: tuple[str, ...]
    interfaces: tuple[str, ...]
    verification: tuple[str, ...]
    evidence_refs: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "requirement_id": self.requirement_id,
            "coverage": self.coverage,
            "capabilities": list(self.capabilities),
            "components": list(self.components),
            "interfaces": list(self.interfaces),
            "verification": list(self.verification),
            "evidence_refs": list(self.evidence_refs),
        }


@dataclass(frozen=True)
class TraceFinding:
    finding_id: str
    severity: TraceSeverity
    subject_id: str
    message: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "finding_id": self.finding_id,
            "severity": self.severity,
            "subject_id": self.subject_id,
            "message": self.message,
        }


@dataclass(frozen=True)
class ArchitectureTrace:
    item_id: str
    item_type: str
    coverage: ArchitectureCoverage
    justified_by: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "item_id": self.item_id,
            "item_type": self.item_type,
            "coverage": self.coverage,
            "justified_by": list(self.justified_by),
        }


@dataclass(frozen=True)
class TraceValidationResult:
    source_compiled_hash: str
    capability_resolution_hash: str
    trace_validator_version: str
    trace_validation_hash: str
    trace_edges: tuple[TraceEdge, ...]
    trace_paths: tuple[TracePath, ...]
    architecture_coverage: tuple[ArchitectureTrace, ...]
    findings: tuple[TraceFinding, ...]
    implementation_gaps: tuple[str, ...]

    @property
    def error_count(self) -> int:
        return sum(1 for finding in self.findings if finding.severity == "ERROR")

    @property
    def warning_count(self) -> int:
        return sum(1 for finding in self.findings if finding.severity == "WARNING")

    @property
    def ok(self) -> bool:
        return self.error_count == 0

    def as_dict(self) -> dict[str, Any]:
        return {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": self.source_compiled_hash,
            "capability_resolution_hash": self.capability_resolution_hash,
            "trace_validator_version": self.trace_validator_version,
            "trace_validation_hash": self.trace_validation_hash,
            "trace_edges": [edge.as_dict() for edge in self.trace_edges],
            "trace_paths": [path.as_dict() for path in self.trace_paths],
            "architecture_coverage": [item.as_dict() for item in self.architecture_coverage],
            "findings": [finding.as_dict() for finding in self.findings],
            "implementation_gaps": list(self.implementation_gaps),
            "summary": {
                "normative_requirements": len(
                    [path for path in self.trace_paths if path.coverage not in {"DEFERRED"}]
                ),
                "covered_requirements": len([path for path in self.trace_paths if path.coverage == "COVERED"]),
                "partially_covered_requirements": len(
                    [path for path in self.trace_paths if path.coverage == "PARTIALLY_COVERED"]
                ),
                "uncovered_requirements": len([path for path in self.trace_paths if path.coverage == "UNCOVERED"]),
                "deferred_requirements": len([path for path in self.trace_paths if path.coverage == "DEFERRED"]),
                "blocked_requirements": len([path for path in self.trace_paths if path.coverage == "BLOCKED"]),
                "justified_components": len(
                    [item for item in self.architecture_coverage if item.item_type == "component" and item.coverage == "JUSTIFIED"]
                ),
                "orphan_components": len(
                    [item for item in self.architecture_coverage if item.item_type == "component" and item.coverage == "ORPHANED"]
                ),
                "justified_interfaces": len(
                    [item for item in self.architecture_coverage if item.item_type == "interface" and item.coverage == "JUSTIFIED"]
                ),
                "orphan_interfaces": len(
                    [item for item in self.architecture_coverage if item.item_type == "interface" and item.coverage == "ORPHANED"]
                ),
                "error_count": self.error_count,
                "warning_count": self.warning_count,
            },
        }


@dataclass(frozen=True)
class GeneratedImplementationTask:
    id: str
    title: str
    objective: str
    implements: dict[str, tuple[str, ...]]
    depends_on: tuple[str, ...]
    write_scope: dict[str, tuple[str, ...]]
    execution: dict[str, str]
    verification: dict[str, Any]
    risk: dict[str, str]
    provenance: dict[str, str]
    fingerprint: str
    epic_id: str
    feature_id: str
    component_id: str | None = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "objective": self.objective,
            "implements": {
                "requirements": list(self.implements["requirements"]),
                "capabilities": list(self.implements["capabilities"]),
                "components": list(self.implements["components"]),
                "interfaces": list(self.implements["interfaces"]),
            },
            "depends_on": list(self.depends_on),
            "write_scope": {
                "allowed": list(self.write_scope["allowed"]),
                "prohibited": list(self.write_scope["prohibited"]),
            },
            "execution": self.execution,
            "verification": self.verification,
            "risk": self.risk,
            "provenance": self.provenance,
            "fingerprint": self.fingerprint,
            "epic_id": self.epic_id,
            "feature_id": self.feature_id,
            "component_id": self.component_id,
        }


@dataclass(frozen=True)
class SatisfiedPlanningUnit:
    id: str
    title: str
    capabilities: tuple[str, ...]
    evidence_refs: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "capabilities": list(self.capabilities),
            "evidence_refs": list(self.evidence_refs),
            "status": "SATISFIED_BY_EXISTING_EVIDENCE",
        }


@dataclass(frozen=True)
class ImplementationPlanFinding:
    finding_id: str
    severity: PlanFindingSeverity
    subject_id: str
    message: str

    def as_dict(self) -> dict[str, str]:
        return {
            "finding_id": self.finding_id,
            "severity": self.severity,
            "subject_id": self.subject_id,
            "message": self.message,
        }


@dataclass(frozen=True)
class ClassifiedTraceWarning:
    finding_id: str
    subject_id: str
    classification: WarningClassification
    message: str

    def as_dict(self) -> dict[str, str]:
        return {
            "finding_id": self.finding_id,
            "subject_id": self.subject_id,
            "classification": self.classification,
            "message": self.message,
        }


@dataclass(frozen=True)
class ImplementationPlan:
    source_compiled_hash: str
    capability_resolution_hash: str
    trace_validation_hash: str
    generator_version: str
    implementation_plan_hash: str
    epics: tuple[dict[str, Any], ...]
    features: tuple[dict[str, Any], ...]
    tasks: tuple[GeneratedImplementationTask, ...]
    satisfied_units: tuple[SatisfiedPlanningUnit, ...]
    dependency_edges: tuple[tuple[str, str], ...]
    waves: tuple[dict[str, Any], ...]
    parallelizable_sets: tuple[dict[str, Any], ...]
    critical_path: tuple[str, ...]
    human_gates: tuple[dict[str, Any], ...]
    findings: tuple[ImplementationPlanFinding, ...]
    warning_classifications: tuple[ClassifiedTraceWarning, ...]

    @property
    def ok(self) -> bool:
        return not any(finding.severity == "ERROR" for finding in self.findings)

    def as_dict(self) -> dict[str, Any]:
        risk_distribution: dict[str, int] = {}
        tasks_by_capability: dict[str, int] = {}
        tasks_by_component: dict[str, int] = {}
        for task in self.tasks:
            risk_level = task.risk["level"]
            risk_distribution[risk_level] = risk_distribution.get(risk_level, 0) + 1
            for capability_id in task.implements["capabilities"]:
                tasks_by_capability[capability_id] = tasks_by_capability.get(capability_id, 0) + 1
            for component_id in task.implements["components"]:
                tasks_by_component[component_id] = tasks_by_component.get(component_id, 0) + 1
        return {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": self.source_compiled_hash,
            "capability_resolution_hash": self.capability_resolution_hash,
            "trace_validation_hash": self.trace_validation_hash,
            "generator_version": self.generator_version,
            "implementation_plan_hash": self.implementation_plan_hash,
            "epics": list(self.epics),
            "features": list(self.features),
            "tasks": [task.as_dict() for task in self.tasks],
            "satisfied_units": [unit.as_dict() for unit in self.satisfied_units],
            "dependency_edges": [list(edge) for edge in self.dependency_edges],
            "waves": list(self.waves),
            "parallelizable_sets": list(self.parallelizable_sets),
            "critical_path": list(self.critical_path),
            "human_gates": list(self.human_gates),
            "findings": [finding.as_dict() for finding in self.findings],
            "warning_classifications": [warning.as_dict() for warning in self.warning_classifications],
            "summary": {
                "epic_count": len(self.epics),
                "feature_count": len(self.features),
                "executable_task_count": len(self.tasks),
                "already_satisfied_planning_units": len(self.satisfied_units),
                "dependency_edge_count": len(self.dependency_edges),
                "wave_count": len(self.waves),
                "maximum_parallel_width": max((len(wave["task_ids"]) for wave in self.waves), default=0),
                "critical_path_task_count": len(self.critical_path),
                "human_gate_count": len(self.human_gates),
                "risk_distribution": dict(sorted(risk_distribution.items())),
                "tasks_by_capability": dict(sorted(tasks_by_capability.items())),
                "tasks_by_component": dict(sorted(tasks_by_component.items())),
                "finding_error_count": len([finding for finding in self.findings if finding.severity == "ERROR"]),
                "finding_warning_count": len([finding for finding in self.findings if finding.severity == "WARNING"]),
            },
        }


def validate_project_manifest(root: Path = PROJECT_MANIFEST_ROOT) -> ManifestValidationResult:
    documents = load_manifest_documents(root)
    errors: list[str] = []
    warnings: list[str] = []

    project = _parse_project(documents, errors)
    source_ids = {source.id for source in project.source_corpus} if project else set()
    source_ids.add("BEAG-001")

    capabilities = _parse_capabilities(documents, errors)
    capability_ids = {capability.id for capability in capabilities}
    _validate_unique_ids(documents, errors)
    _validate_source_refs(documents, source_ids, errors)
    _validate_capability_dependencies(capabilities, capability_ids, errors)

    requirements = _items(documents, "requirements")
    components = _items(documents, "components")
    interfaces = _items(documents, "interfaces")
    agents = _items(documents, "agents")
    epics = _items(documents, "epics")
    features = _items(documents, "features")

    for item in [*requirements, *components, *agents]:
        _validate_capability_refs(item, capability_ids, errors)
    component_ids = {_item_id(component) for component in components}
    requirement_ids = {_item_id(requirement) for requirement in requirements}
    epic_ids = {_item_id(epic) for epic in epics}
    _validate_interfaces(interfaces, component_ids, errors)
    _validate_feature_refs(features, epic_ids, requirement_ids, errors)

    selected = tuple(sorted(capability.id for capability in capabilities if capability.status in {"REQUIRED", "CONDITIONAL"}))
    already = tuple(sorted(capability.id for capability in capabilities if capability.maturity in {"VALIDATED", "PRODUCTION_READY"}))
    missing = tuple(
        sorted(
            capability.id
            for capability in capabilities
            if capability.status == "REQUIRED" and capability.maturity not in {"VALIDATED", "PRODUCTION_READY"}
        )
    )
    unresolved = _unresolved_decisions(documents)
    if not unresolved:
        warnings.append("no unresolved decisions recorded")

    return ManifestValidationResult(
        manifest_files=tuple(sorted(str(path.relative_to(root)) for path in documents)),
        requirements_count=len(requirements),
        components_count=len(components),
        interfaces_count=len(interfaces),
        capabilities_selected=selected,
        unresolved_decisions=tuple(unresolved),
        validation_errors=tuple(errors),
        validation_warnings=tuple(warnings),
        already_satisfied=already,
        still_missing=missing,
        compilation_hash=compilation_hash(documents),
    )


def load_manifest_documents(root: Path) -> dict[Path, dict[str, Any]]:
    if not root.exists():
        raise FileNotFoundError(f"project manifest root not found: {root}")
    documents: dict[Path, dict[str, Any]] = {}
    for path in sorted(root.rglob("*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(loaded, dict):
            raise TypeError(f"{path} must contain a YAML mapping")
        documents[path] = loaded
    return documents


def compile_project_manifest(root: Path = PROJECT_MANIFEST_ROOT) -> CompilationResult:
    validation = validate_project_manifest(root)
    if not validation.ok:
        raise ValueError("project manifest validation failed: " + "; ".join(validation.validation_errors))
    documents = load_manifest_documents(root)
    compiled = _compile_documents(root, documents)
    compiled_bytes = canonical_bytes(compiled.as_dict())
    compiled_hash = hashlib.sha256(compiled_bytes).hexdigest()
    lock = ManifestLock(
        project_id=str(compiled.project["id"]),
        manifest_schema_version=PROJECT_MANIFEST_SCHEMA_VERSION,
        compiler_version=PROJECT_MANIFEST_COMPILER_VERSION,
        source_file_hashes=_source_file_hashes(root, documents),
        source_compilation_hash=validation.compilation_hash,
        compiled_hash=compiled_hash,
    )
    return CompilationResult(
        compiled=compiled,
        lock=lock,
        compiled_bytes=compiled_bytes,
        validation=validation,
    )


def write_compiled_project(root: Path = PROJECT_MANIFEST_ROOT, output_dir: Path = Path(".build/compiled")) -> CompilationResult:
    result = compile_project_manifest(root)
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "project.json", result.compiled.as_dict())
    _write_json(output_dir / "manifest.lock", result.lock.as_dict())
    _write_json(output_dir / "requirements.json", {"requirements": list(result.compiled.requirements)})
    _write_json(output_dir / "architecture.json", result.compiled.architecture)
    _write_json(output_dir / "capabilities.json", {"capabilities": list(result.compiled.capabilities)})
    _write_json(output_dir / "planning.json", result.compiled.planning)
    return result


def resolve_capabilities(root: Path = PROJECT_MANIFEST_ROOT) -> CapabilityResolution:
    compilation = compile_project_manifest(root)
    return resolve_compiled_capabilities(compilation)


def resolve_compiled_capabilities(compilation: CompilationResult) -> CapabilityResolution:
    compiled = compilation.compiled.as_dict()
    capability_rows = {str(item["id"]): item for item in compilation.compiled.capabilities}
    capability_ids = set(capability_rows)
    _validate_capability_graph_inputs(capability_rows)

    direct_dependencies: dict[str, set[str]] = {}
    applied_conditionals: dict[str, list[dict[str, Any]]] = {}
    for capability_id, row in capability_rows.items():
        direct_dependencies[capability_id] = {str(item) for item in row.get("depends_on", [])}
        applied_conditionals[capability_id] = []
        for conditional in row.get("conditional_dependencies", []):
            if not isinstance(conditional, dict):
                raise TypeError(f"{capability_id} conditional dependency must be a mapping")
            dependencies = [str(item) for item in conditional.get("capabilities", [])]
            for dependency in dependencies:
                if dependency not in capability_ids:
                    raise ValueError(f"{capability_id} conditional dependency references unknown capability {dependency}")
            if _condition_matches(compiled, conditional.get("condition", {})):
                direct_dependencies[capability_id].update(dependencies)
                applied_conditionals[capability_id].append(_normalize(conditional))
        for dependency in direct_dependencies[capability_id]:
            if dependency not in capability_ids:
                raise ValueError(f"{capability_id} depends on unknown capability {dependency}")
            if dependency == capability_id:
                raise ValueError(f"{capability_id} cannot depend on itself")

    cycle = _capability_cycle(direct_dependencies)
    if cycle:
        raise ValueError(f"capability dependency cycle: {' -> '.join(cycle)}")

    transitive = {
        capability_id: tuple(sorted(_transitive_dependencies(capability_id, direct_dependencies)))
        for capability_id in sorted(capability_ids)
    }
    required = _required_capability_set(capability_rows, direct_dependencies)
    capabilities = tuple(
        _resolve_capability(
            row,
            direct_dependencies[str(row["id"])],
            transitive[str(row["id"])],
            applied_conditionals[str(row["id"])],
            required,
        )
        for row in sorted(capability_rows.values(), key=lambda item: str(item["id"]))
    )
    direct_edges = tuple(
        sorted((capability_id, dependency) for capability_id, dependencies in direct_dependencies.items() for dependency in dependencies)
    )
    transitive_edges = tuple(
        sorted((capability_id, dependency) for capability_id, dependencies in transitive.items() for dependency in dependencies)
    )
    partial = tuple(sorted(capability.capability_id for capability in capabilities if capability.satisfaction == "PARTIALLY_SATISFIED"))
    satisfied = tuple(sorted(capability.capability_id for capability in capabilities if capability.satisfaction == "SATISFIED"))
    unsatisfied = tuple(sorted(capability.capability_id for capability in capabilities if capability.satisfaction == "UNSATISFIED"))
    deferred = tuple(sorted(capability.capability_id for capability in capabilities if capability.satisfaction in {"DEFERRED", "NOT_APPLICABLE"}))
    blocked = tuple(sorted(capability.capability_id for capability in capabilities if capability.blockers))

    payload = {
        "source_compiled_hash": compilation.lock.compiled_hash,
        "resolver_version": CAPABILITY_RESOLVER_VERSION,
        "capabilities": [capability.as_dict() for capability in capabilities],
        "direct_edges": [list(edge) for edge in direct_edges],
        "transitive_edges": [list(edge) for edge in transitive_edges],
        "required_capabilities": sorted(required),
        "conditional_capabilities_activated": sorted(
            capability_id for capability_id, conditionals in applied_conditionals.items() if conditionals
        ),
        "deferred_capabilities": list(deferred),
        "satisfied_capabilities": list(satisfied),
        "partially_satisfied_capabilities": list(partial),
        "unsatisfied_capabilities": list(unsatisfied),
        "blocked_capabilities": list(blocked),
    }
    resolution_hash = hashlib.sha256(canonical_bytes(payload)).hexdigest()
    return CapabilityResolution(
        source_compiled_hash=compilation.lock.compiled_hash,
        resolver_version=CAPABILITY_RESOLVER_VERSION,
        capability_resolution_hash=resolution_hash,
        capabilities=capabilities,
        direct_edges=direct_edges,
        transitive_edges=transitive_edges,
        required_capabilities=tuple(sorted(required)),
        conditional_capabilities_activated=tuple(payload["conditional_capabilities_activated"]),
        deferred_capabilities=deferred,
        satisfied_capabilities=satisfied,
        partially_satisfied_capabilities=partial,
        unsatisfied_capabilities=unsatisfied,
        blocked_capabilities=blocked,
    )


def write_capability_resolution(
    root: Path = PROJECT_MANIFEST_ROOT,
    output_dir: Path = Path(".build/compiled"),
) -> CapabilityResolution:
    resolution = resolve_capabilities(root)
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "capability-resolution.json", resolution.as_dict())
    _write_json(
        output_dir / "capability-graph.json",
        {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": resolution.source_compiled_hash,
            "resolver_version": resolution.resolver_version,
            "capability_resolution_hash": resolution.capability_resolution_hash,
            "direct_edges": [list(edge) for edge in resolution.direct_edges],
            "transitive_edges": [list(edge) for edge in resolution.transitive_edges],
        },
    )
    _write_json(
        output_dir / "capability-gaps.json",
        {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": resolution.source_compiled_hash,
            "resolver_version": resolution.resolver_version,
            "capability_resolution_hash": resolution.capability_resolution_hash,
            "required_capabilities": list(resolution.required_capabilities),
            "satisfied_capabilities": list(resolution.satisfied_capabilities),
            "partially_satisfied_capabilities": list(resolution.partially_satisfied_capabilities),
            "unsatisfied_capabilities": list(resolution.unsatisfied_capabilities),
            "deferred_capabilities": list(resolution.deferred_capabilities),
            "blocked_capabilities": list(resolution.blocked_capabilities),
        },
    )
    return resolution


def validate_traces(root: Path = PROJECT_MANIFEST_ROOT) -> TraceValidationResult:
    compilation = compile_project_manifest(root)
    resolution = resolve_compiled_capabilities(compilation)
    return validate_compiled_traces(compilation, resolution)


def validate_compiled_traces(
    compilation: CompilationResult,
    resolution: CapabilityResolution,
) -> TraceValidationResult:
    compiled = compilation.compiled
    capability_by_id = {capability.capability_id: capability for capability in resolution.capabilities}
    components = [dict(item) for item in compiled.architecture.get("components", [])]
    interfaces = [dict(item) for item in compiled.architecture.get("interfaces", [])]
    gates = [dict(item) for item in compiled.verification.get("verification", {}).get("gates", [])]
    decisions = [dict(item) for item in compilation.compiled.as_dict().get("planning", {}).get("decisions", [])]
    requirements = [dict(item) for item in compiled.requirements]
    deployment_mode = str(compiled.deployment.get("deployment", {}).get("current_mode", ""))

    edges: list[TraceEdge] = []
    paths: list[TracePath] = []
    findings: list[TraceFinding] = []
    gaps: set[str] = set()

    component_by_capability = _items_by_capability(components)
    interface_by_component = _interfaces_by_component(interfaces)
    gates_by_source = _items_by_source(gates)

    for requirement in sorted(requirements, key=lambda item: str(item.get("id", ""))):
        requirement_id = str(requirement["id"])
        classification = requirement.get("classification")
        if classification == "FUTURE/DEFERRED":
            paths.append(
                TracePath(requirement_id, "DEFERRED", tuple(requirement.get("capabilities", [])), (), (), (), ())
            )
            findings.append(
                TraceFinding(
                    f"TRACE-{requirement_id}-DEFERRED",
                    "INFO",
                    requirement_id,
                    "requirement deferred from current implementation",
                )
            )
            continue
        capabilities = tuple(sorted(str(item) for item in requirement.get("capabilities", [])))
        components_for_requirement = tuple(sorted({
            component_id
            for capability_id in capabilities
            for component_id in component_by_capability.get(capability_id, set())
        }))
        interfaces_for_requirement = tuple(sorted({
            interface_id
            for component_id in components_for_requirement
            for interface_id in interface_by_component.get(component_id, set())
        }))
        verification_for_requirement = tuple(sorted({
            gate_id
            for source_ref in requirement.get("source_refs", [])
            for gate_id in gates_by_source.get(str(source_ref), set())
        }))
        evidence = tuple(sorted({
            evidence_ref
            for capability_id in capabilities
            for evidence_ref in capability_by_id.get(capability_id, _empty_capability(capability_id)).evidence_refs
        }))
        for capability_id in capabilities:
            edges.append(TraceEdge(requirement_id, capability_id, "REQUIRES_CAPABILITY"))
        for component_id in components_for_requirement:
            edges.append(TraceEdge(requirement_id, component_id, "IMPLEMENTED_BY_COMPONENT"))
        for interface_id in interfaces_for_requirement:
            edges.append(TraceEdge(requirement_id, interface_id, "EXPOSED_BY_INTERFACE"))
        for gate_id in verification_for_requirement:
            edges.append(TraceEdge(requirement_id, gate_id, "VERIFIED_BY"))
        for evidence_ref in evidence:
            edges.append(TraceEdge(requirement_id, evidence_ref, "EVIDENCED_BY"))

        coverage = _requirement_coverage(
            requirement,
            capabilities,
            components_for_requirement,
            verification_for_requirement,
            capability_by_id,
        )
        paths.append(
            TracePath(
                requirement_id,
                coverage,
                capabilities,
                components_for_requirement,
                interfaces_for_requirement,
                verification_for_requirement,
                evidence,
            )
        )
        _requirement_findings(
            requirement,
            coverage,
            components_for_requirement,
            verification_for_requirement,
            capability_by_id,
            findings,
            gaps,
            deployment_mode,
        )

    architecture = _architecture_coverage(components, interfaces, requirements, decisions, edges, findings)
    payload = {
        "source_compiled_hash": compilation.lock.compiled_hash,
        "capability_resolution_hash": resolution.capability_resolution_hash,
        "trace_validator_version": TRACE_VALIDATOR_VERSION,
        "trace_edges": [edge.as_dict() for edge in sorted(edges, key=lambda item: (item.source_id, item.edge_type, item.target_id))],
        "trace_paths": [path.as_dict() for path in sorted(paths, key=lambda item: item.requirement_id)],
        "architecture_coverage": [item.as_dict() for item in sorted(architecture, key=lambda item: (item.item_type, item.item_id))],
        "findings": [finding.as_dict() for finding in sorted(findings, key=lambda item: item.finding_id)],
        "implementation_gaps": sorted(gaps),
    }
    trace_hash = hashlib.sha256(canonical_bytes(payload)).hexdigest()
    return TraceValidationResult(
        source_compiled_hash=compilation.lock.compiled_hash,
        capability_resolution_hash=resolution.capability_resolution_hash,
        trace_validator_version=TRACE_VALIDATOR_VERSION,
        trace_validation_hash=trace_hash,
        trace_edges=tuple(TraceEdge(**item) for item in payload["trace_edges"]),
        trace_paths=tuple(TracePath(**item) for item in payload["trace_paths"]),
        architecture_coverage=tuple(ArchitectureTrace(**item) for item in payload["architecture_coverage"]),
        findings=tuple(TraceFinding(**item) for item in payload["findings"]),
        implementation_gaps=tuple(payload["implementation_gaps"]),
    )


def write_trace_validation(
    root: Path = PROJECT_MANIFEST_ROOT,
    output_dir: Path = Path(".build/compiled"),
) -> TraceValidationResult:
    result = validate_traces(root)
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "trace-validation.json", result.as_dict())
    _write_json(
        output_dir / "trace-graph.json",
        {
            "generated": GENERATED_MARKER,
            "source_compiled_hash": result.source_compiled_hash,
            "capability_resolution_hash": result.capability_resolution_hash,
            "trace_validator_version": result.trace_validator_version,
            "trace_validation_hash": result.trace_validation_hash,
            "trace_edges": [edge.as_dict() for edge in result.trace_edges],
        },
    )
    _write_json(
        output_dir / "requirement-coverage.json",
        {
            "generated": GENERATED_MARKER,
            "trace_validation_hash": result.trace_validation_hash,
            "trace_paths": [path.as_dict() for path in result.trace_paths],
        },
    )
    _write_json(
        output_dir / "architecture-coverage.json",
        {
            "generated": GENERATED_MARKER,
            "trace_validation_hash": result.trace_validation_hash,
            "architecture_coverage": [item.as_dict() for item in result.architecture_coverage],
        },
    )
    _write_json(
        output_dir / "implementation-gaps.json",
        {
            "generated": GENERATED_MARKER,
            "trace_validation_hash": result.trace_validation_hash,
            "implementation_gaps": list(result.implementation_gaps),
            "findings": [finding.as_dict() for finding in result.findings],
        },
    )
    return result


def generate_implementation_plan(root: Path = PROJECT_MANIFEST_ROOT) -> ImplementationPlan:
    compilation = compile_project_manifest(root)
    resolution = resolve_compiled_capabilities(compilation)
    trace = validate_compiled_traces(compilation, resolution)
    return generate_compiled_implementation_plan(compilation, resolution, trace)


def generate_compiled_implementation_plan(
    compilation: CompilationResult,
    resolution: CapabilityResolution,
    trace: TraceValidationResult,
) -> ImplementationPlan:
    if not trace.ok:
        raise ValueError("trace validation failed; implementation DAG generation is blocked")

    compiled = compilation.compiled
    capabilities = {capability.capability_id: capability for capability in resolution.capabilities}
    components = {
        str(component["id"]): component
        for component in compiled.architecture.get("components", [])
        if component.get("classification") != "FUTURE/DEFERRED"
    }
    component_by_capability = _items_by_capability(list(components.values()))
    requirements_by_capability = _requirements_by_capability([dict(requirement) for requirement in compiled.requirements])
    trace_path_by_requirement = {path.requirement_id: path for path in trace.trace_paths}

    gap_capabilities = tuple(
        capability_id
        for capability_id in sorted(trace.implementation_gaps)
        if capabilities[capability_id].satisfaction not in {"DEFERRED", "NOT_APPLICABLE", "SATISFIED"}
    )
    epics = _planned_epics(compiled, gap_capabilities)
    features = _planned_features(compiled, gap_capabilities)
    satisfied_units = _satisfied_planning_units(resolution)
    task_specs = _generated_task_specs(
        compilation,
        resolution,
        trace,
        gap_capabilities,
        capabilities,
        components,
        component_by_capability,
        requirements_by_capability,
        trace_path_by_requirement,
    )
    tasks_without_dependencies = tuple(_task_from_spec(spec) for spec in task_specs)
    dependency_edges = _implementation_dependency_edges(tasks_without_dependencies, resolution)
    dependency_by_task: dict[str, tuple[str, ...]] = {
        task.id: tuple(sorted(dependency for task_id, dependency in dependency_edges if task_id == task.id))
        for task in tasks_without_dependencies
    }
    tasks = tuple(
        _replace_task_dependencies(task, dependency_by_task.get(task.id, ()))
        for task in tasks_without_dependencies
    )
    findings = _validate_implementation_plan(tasks, dependency_edges, gap_capabilities)
    if any(finding.severity == "ERROR" for finding in findings):
        raise ValueError("generated implementation DAG is invalid")
    waves = _implementation_waves(tasks, dependency_edges)
    parallelizable_sets = _parallelizable_sets(tasks, waves)
    critical_path = _critical_path(tasks, dependency_edges)
    human_gates = _human_gates(tasks)
    warning_classifications = _classify_trace_warnings(trace.findings)
    payload = {
        "source_compiled_hash": compilation.lock.compiled_hash,
        "capability_resolution_hash": resolution.capability_resolution_hash,
        "trace_validation_hash": trace.trace_validation_hash,
        "generator_version": IMPLEMENTATION_DAG_GENERATOR_VERSION,
        "epics": epics,
        "features": features,
        "tasks": [task.as_dict() for task in tasks],
        "satisfied_units": [unit.as_dict() for unit in satisfied_units],
        "dependency_edges": [list(edge) for edge in dependency_edges],
        "waves": waves,
        "parallelizable_sets": parallelizable_sets,
        "critical_path": list(critical_path),
        "human_gates": human_gates,
        "findings": [finding.as_dict() for finding in findings],
        "warning_classifications": [warning.as_dict() for warning in warning_classifications],
    }
    plan_hash = hashlib.sha256(canonical_bytes(payload)).hexdigest()
    return ImplementationPlan(
        source_compiled_hash=compilation.lock.compiled_hash,
        capability_resolution_hash=resolution.capability_resolution_hash,
        trace_validation_hash=trace.trace_validation_hash,
        generator_version=IMPLEMENTATION_DAG_GENERATOR_VERSION,
        implementation_plan_hash=plan_hash,
        epics=tuple(epics),
        features=tuple(features),
        tasks=tasks,
        satisfied_units=satisfied_units,
        dependency_edges=dependency_edges,
        waves=tuple(waves),
        parallelizable_sets=tuple(parallelizable_sets),
        critical_path=critical_path,
        human_gates=tuple(human_gates),
        findings=findings,
        warning_classifications=warning_classifications,
    )


def write_implementation_plan(
    root: Path = PROJECT_MANIFEST_ROOT,
    output_dir: Path = Path(".build/compiled"),
) -> ImplementationPlan:
    plan = generate_implementation_plan(root)
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_tasks = output_dir / "generated-tasks"
    generated_tasks.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "implementation-plan.json", plan.as_dict())
    _write_json(
        output_dir / "implementation-dag.json",
        {
            "generated": GENERATED_MARKER,
            "implementation_plan_hash": plan.implementation_plan_hash,
            "dependency_edges": [list(edge) for edge in plan.dependency_edges],
            "tasks": [task.id for task in plan.tasks],
        },
    )
    _write_json(
        output_dir / "implementation-waves.json",
        {
            "generated": GENERATED_MARKER,
            "implementation_plan_hash": plan.implementation_plan_hash,
            "waves": list(plan.waves),
            "parallelizable_sets": list(plan.parallelizable_sets),
        },
    )
    _write_json(
        output_dir / "critical-path.json",
        {
            "generated": GENERATED_MARKER,
            "implementation_plan_hash": plan.implementation_plan_hash,
            "critical_path": list(plan.critical_path),
            "critical_path_length": len(plan.critical_path),
        },
    )
    _write_json(
        output_dir / "human-gates.json",
        {
            "generated": GENERATED_MARKER,
            "implementation_plan_hash": plan.implementation_plan_hash,
            "human_gates": list(plan.human_gates),
        },
    )
    _write_json(
        output_dir / "task-generation-findings.json",
        {
            "generated": GENERATED_MARKER,
            "implementation_plan_hash": plan.implementation_plan_hash,
            "findings": [finding.as_dict() for finding in plan.findings],
            "warning_classifications": [warning.as_dict() for warning in plan.warning_classifications],
        },
    )
    for stale in generated_tasks.glob("*.json"):
        stale.unlink()
    for task in plan.tasks:
        _write_json(generated_tasks / f"{task.id}.json", task.as_dict())
    return plan


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(_normalize(value), sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")


def compilation_hash(documents: dict[Path, dict[str, Any]]) -> str:
    normalized = {
        str(path): documents[path]
        for path in sorted(documents, key=lambda item: str(item))
    }
    payload = json.dumps(normalized, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _compile_documents(root: Path, documents: dict[Path, dict[str, Any]]) -> CompiledProject:
    project_path = root / "project.yaml"
    project_document = documents[project_path]
    project = _with_source(_normalize(project_document), root, project_path)
    intake_path = root / "intake.yaml"
    intake = _with_source(_normalize(documents[intake_path]), root, intake_path)
    capabilities_path = root / "capabilities.yaml"
    capabilities = tuple(
        _with_source(item, root, capabilities_path)
        for item in _sort_by_id(_normalize(_document_named(documents, "capabilities.yaml")).get("capabilities", []))
    )
    requirements = tuple(
        _with_source(requirement, root, path)
        for path in sorted(documents)
        for requirement in _sort_by_id(_normalize(documents[path]).get("requirements", []))
    )
    agents = _merged_items(root, documents, "agents", include_paths=("agents.yaml",))
    models = _merged_items(root, documents, "models")
    tools = _merged_items(root, documents, "tools")
    operations = _merged_items(root, documents, "operations")
    architecture = {
        "components": list(_merged_items(root, documents, "components")),
        "interfaces": list(_merged_items(root, documents, "interfaces")),
        "data_objects": list(_merged_items(root, documents, "data_objects")),
        "agent_topology": _normalize(_document_by_relative_path(root, documents, "architecture/agent-topology.yaml").get("agents", [])),
        "deployment": _normalize(_document_by_relative_path(root, documents, "architecture/deployment.yaml").get("deployment", {})),
        "security_controls": list(_merged_items(root, documents, "security_controls")),
        "system_flow": _normalize(_document_by_relative_path(root, documents, "architecture/system.yaml").get("flow", [])),
    }
    planning = {
        "roadmap": _normalize(_document_by_relative_path(root, documents, "planning/roadmap.yaml").get("roadmap", [])),
        "epics": _normalize(_document_by_relative_path(root, documents, "planning/epics.yaml").get("epics", [])),
        "features": _normalize(_document_by_relative_path(root, documents, "planning/features.yaml").get("features", [])),
        "task_graph": _normalize(_document_by_relative_path(root, documents, "planning/task-graph.yaml").get("task_graph", {})),
        "implementation_waves": _normalize(
            _document_by_relative_path(root, documents, "planning/implementation-waves.yaml").get("implementation_waves", [])
        ),
    }
    return CompiledProject(
        project=project,
        intake=intake,
        requirements=requirements,
        architecture=_normalize(architecture),
        capabilities=capabilities,
        agents=agents,
        models=models,
        tools=tools,
        verification=_with_source(_normalize(_document_named(documents, "verification.yaml")), root, _path_named(documents, "verification.yaml")),
        repository=_with_source(_normalize(documents[root / "repository.yaml"]), root, root / "repository.yaml"),
        deployment=_with_source(_normalize(documents[root / "deployment.yaml"]), root, root / "deployment.yaml"),
        operations=operations,
        planning=_normalize(planning),
        source_metadata={
            "source_files": sorted(str(path.relative_to(root)) for path in documents),
            "source_file_count": len(documents),
            "source_file_hashes": _source_file_hashes(root, documents),
        },
    )


def _normalize(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            str(key): _normalize(value[key])
            for key in sorted(value)
            if value[key] is not None
        }
    if isinstance(value, list):
        normalized = [_normalize(item) for item in value]
        if all(isinstance(item, str) for item in normalized):
            return sorted(normalized)
        return normalized
    if isinstance(value, str):
        return value.strip()
    return value


def _sort_by_id(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    mappings = [item for item in items if isinstance(item, dict)]
    return sorted(mappings, key=lambda item: str(item.get("id", "")))


def _merged_items(
    root: Path,
    documents: dict[Path, dict[str, Any]],
    key: str,
    *,
    include_paths: tuple[str, ...] | None = None,
) -> tuple[dict[str, Any], ...]:
    items: list[dict[str, Any]] = []
    for path in sorted(documents):
        if include_paths is not None and str(path.relative_to(root)) not in include_paths:
            continue
        raw = _normalize(documents[path]).get(key)
        if isinstance(raw, list):
            items.extend(_with_source(item, root, path) for item in _sort_by_id(raw))
    return tuple(sorted(items, key=lambda item: str(item.get("id", ""))))


def _with_source(item: dict[str, Any], root: Path, path: Path) -> dict[str, Any]:
    enriched = dict(item)
    enriched["source_manifest_file"] = str(path.relative_to(root))
    return enriched


def _document_named(documents: dict[Path, dict[str, Any]], name: str) -> dict[str, Any]:
    return documents[_path_named(documents, name)]


def _path_named(documents: dict[Path, dict[str, Any]], name: str) -> Path:
    matches = [path for path in documents if path.name == name]
    if len(matches) != 1:
        raise ValueError(f"expected exactly one {name}, found {len(matches)}")
    return matches[0]


def _document_by_relative_path(root: Path, documents: dict[Path, dict[str, Any]], relative_path: str) -> dict[str, Any]:
    path = root / relative_path
    return documents[path]


def _source_file_hashes(root: Path, documents: dict[Path, dict[str, Any]]) -> dict[str, str]:
    return {
        str(path.relative_to(root)): hashlib.sha256(canonical_bytes(documents[path])).hexdigest()
        for path in sorted(documents)
    }


def _write_json(path: Path, value: Any) -> None:
    path.write_bytes(canonical_bytes(value) + b"\n")


def _items_by_capability(items: list[dict[str, Any]]) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for item in items:
        for capability_id in item.get("capabilities", []):
            result.setdefault(str(capability_id), set()).add(str(item["id"]))
        capability_id = item.get("capability")
        if capability_id is not None:
            result.setdefault(str(capability_id), set()).add(str(item["id"]))
    return result


def _interfaces_by_component(interfaces: list[dict[str, Any]]) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for interface in interfaces:
        interface_id = str(interface["id"])
        for endpoint in (interface.get("from_component"), interface.get("to_component")):
            if endpoint is not None:
                result.setdefault(str(endpoint), set()).add(interface_id)
    return result


def _items_by_source(items: list[dict[str, Any]]) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for item in items:
        for source_ref in item.get("source_refs", []):
            result.setdefault(str(source_ref), set()).add(str(item["id"]))
    return result


def _empty_capability(capability_id: str) -> ResolvedCapability:
    return ResolvedCapability(
        capability_id=capability_id,
        name=capability_id,
        declared_status="NOT_REQUIRED",
        resolved_status="NOT_REQUIRED",
        maturity="NOT_IMPLEMENTED",
        satisfaction="NOT_APPLICABLE",
        direct_dependencies=(),
        transitive_dependencies=(),
        conditional_dependencies_applied=(),
        evidence_refs=(),
        missing_requirements_components=(),
        blockers=(),
        source_provenance=(),
    )


def _requirement_coverage(
    requirement: dict[str, Any],
    capabilities: tuple[str, ...],
    components: tuple[str, ...],
    verification: tuple[str, ...],
    capability_by_id: dict[str, ResolvedCapability],
) -> RequirementCoverage:
    if requirement.get("classification") == "FUTURE/DEFERRED":
        return "DEFERRED"
    if not capabilities or any(capability_id not in capability_by_id for capability_id in capabilities):
        return "INVALID"
    if not components or not verification:
        return "UNCOVERED"
    satisfactions = [capability_by_id[capability_id].satisfaction for capability_id in capabilities]
    if any(satisfaction == "UNSATISFIED" for satisfaction in satisfactions):
        return "BLOCKED"
    if any(satisfaction == "PARTIALLY_SATISFIED" for satisfaction in satisfactions):
        return "PARTIALLY_COVERED"
    return "COVERED"


def _requirement_findings(
    requirement: dict[str, Any],
    coverage: RequirementCoverage,
    components: tuple[str, ...],
    verification: tuple[str, ...],
    capability_by_id: dict[str, ResolvedCapability],
    findings: list[TraceFinding],
    gaps: set[str],
    deployment_mode: str,
) -> None:
    requirement_id = str(requirement["id"])
    if coverage == "INVALID":
        findings.append(TraceFinding(f"TRACE-{requirement_id}-INVALID", "ERROR", requirement_id, "invalid requirement capability reference"))
        return
    if coverage == "DEFERRED":
        findings.append(TraceFinding(f"TRACE-{requirement_id}-DEFERRED", "INFO", requirement_id, "requirement deferred from current implementation"))
        return
    if not components:
        findings.append(TraceFinding(f"TRACE-{requirement_id}-NO-ARCH", "ERROR", requirement_id, "normative requirement has no architecture path"))
    if not verification:
        findings.append(TraceFinding(f"TRACE-{requirement_id}-NO-VERIFY", "ERROR", requirement_id, "normative requirement has no verification path"))
    for capability_id in requirement.get("capabilities", []):
        capability = capability_by_id.get(str(capability_id))
        if capability is not None and capability.satisfaction in {"UNSATISFIED", "PARTIALLY_SATISFIED"}:
            gaps.add(str(capability_id))
            findings.append(
                TraceFinding(
                    f"TRACE-{requirement_id}-{capability_id}-GAP",
                    "WARNING",
                    requirement_id,
                    f"requirement depends on {capability_id} with {capability.satisfaction}",
                )
            )
    title = str(requirement.get("title", "")).lower()
    if "authentication" in title or "authenticated" in title:
        has_auth_component = any(capability_id == "C14" for capability_id in requirement.get("capabilities", []))
        if not has_auth_component:
            findings.append(
                TraceFinding(
                    f"TRACE-{requirement_id}-AUTH-ARCH",
                    "ERROR",
                    requirement_id,
                    "authentication requirement lacks user/tenant management capability",
                )
            )
    if "production" in title and "deployment" in title and deployment_mode == "local_development":
        findings.append(
            TraceFinding(
                f"TRACE-{requirement_id}-DEPLOYMENT-CONFLICT",
                "ERROR",
                requirement_id,
                "current-release production deployment requirement conflicts with local_development deployment mode",
            )
        )


def _architecture_coverage(
    components: list[dict[str, Any]],
    interfaces: list[dict[str, Any]],
    requirements: list[dict[str, Any]],
    decisions: list[dict[str, Any]],
    edges: list[TraceEdge],
    findings: list[TraceFinding],
) -> tuple[ArchitectureTrace, ...]:
    requirement_by_capability = _requirements_by_capability(requirements)
    decision_sources = {str(source) for decision in decisions for source in decision.get("source_refs", [])}
    coverage: list[ArchitectureTrace] = []
    for component in sorted(components, key=lambda item: str(item["id"])):
        component_id = str(component["id"])
        if component.get("classification") == "FUTURE/DEFERRED":
            coverage.append(ArchitectureTrace(component_id, "component", "DEFERRED", tuple(component.get("source_refs", []))))
            continue
        justified_by = sorted({
            requirement_id
            for capability_id in component.get("capabilities", [])
            for requirement_id in requirement_by_capability.get(str(capability_id), set())
        })
        if not justified_by:
            justified_by = sorted({str(source) for source in component.get("source_refs", [])} & decision_sources)
        if justified_by:
            coverage.append(ArchitectureTrace(component_id, "component", "JUSTIFIED", tuple(justified_by)))
            for requirement_id in justified_by:
                edges.append(TraceEdge(component_id, requirement_id, "JUSTIFIED_BY"))
        else:
            coverage.append(ArchitectureTrace(component_id, "component", "ORPHANED", ()))
            findings.append(TraceFinding(f"TRACE-{component_id}-ORPHAN", "ERROR", component_id, "normative component is orphaned"))
    component_ids = {str(component["id"]) for component in components}
    for interface in sorted(interfaces, key=lambda item: str(item["id"])):
        interface_id = str(interface["id"])
        if interface.get("classification") == "FUTURE/DEFERRED":
            coverage.append(ArchitectureTrace(interface_id, "interface", "DEFERRED", tuple(interface.get("source_refs", []))))
            continue
        endpoints = [str(interface.get("from_component")), str(interface.get("to_component"))]
        if all(endpoint in component_ids for endpoint in endpoints):
            coverage.append(ArchitectureTrace(interface_id, "interface", "JUSTIFIED", tuple(endpoints)))
            for endpoint in endpoints:
                edges.append(TraceEdge(interface_id, endpoint, "JUSTIFIED_BY"))
        else:
            coverage.append(ArchitectureTrace(interface_id, "interface", "ORPHANED", ()))
            findings.append(TraceFinding(f"TRACE-{interface_id}-ORPHAN", "ERROR", interface_id, "interface endpoint is unknown"))
    return tuple(coverage)


def _requirements_by_capability(requirements: list[dict[str, Any]]) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for requirement in requirements:
        if requirement.get("classification") == "FUTURE/DEFERRED":
            continue
        for capability_id in requirement.get("capabilities", []):
            result.setdefault(str(capability_id), set()).add(str(requirement["id"]))
    return result


def _planned_epics(compiled: CompiledProject, gap_capabilities: tuple[str, ...]) -> list[dict[str, Any]]:
    gap_set = set(gap_capabilities)
    epics = [
        _normalize(epic)
        for epic in compiled.planning.get("epics", [])
        if gap_set.intersection(str(capability_id) for capability_id in epic.get("capabilities", []))
    ]
    return sorted(epics, key=lambda item: str(item.get("id", "")))


def _planned_features(compiled: CompiledProject, gap_capabilities: tuple[str, ...]) -> list[dict[str, Any]]:
    requirement_ids = {
        str(requirement["id"])
        for requirement in compiled.requirements
        if {str(capability_id) for capability_id in requirement.get("capabilities", [])}.intersection(gap_capabilities)
        and requirement.get("classification") != "FUTURE/DEFERRED"
    }
    features = [
        _normalize(feature)
        for feature in compiled.planning.get("features", [])
        if requirement_ids.intersection(str(requirement_id) for requirement_id in feature.get("requirements", []))
    ]
    if not features:
        features = [
            {
                "id": "FEA-GEN-001",
                "title": "Generated remaining implementation plan",
                "epic": "EPC-003",
                "requirements": sorted(requirement_ids),
            }
        ]
    return sorted(features, key=lambda item: str(item.get("id", "")))


def _satisfied_planning_units(resolution: CapabilityResolution) -> tuple[SatisfiedPlanningUnit, ...]:
    units = []
    for capability in resolution.capabilities:
        if capability.satisfaction == "SATISFIED":
            units.append(
                SatisfiedPlanningUnit(
                    id=f"SAT-{capability.capability_id}",
                    title=f"{capability.capability_id} {capability.name}",
                    capabilities=(capability.capability_id,),
                    evidence_refs=capability.evidence_refs,
                )
            )
    return tuple(sorted(units, key=lambda item: item.id))


def _generated_task_specs(
    compilation: CompilationResult,
    resolution: CapabilityResolution,
    trace: TraceValidationResult,
    gap_capabilities: tuple[str, ...],
    capabilities: dict[str, ResolvedCapability],
    components: dict[str, dict[str, Any]],
    component_by_capability: dict[str, set[str]],
    requirements_by_capability: dict[str, set[str]],
    trace_path_by_requirement: dict[str, TracePath],
) -> list[dict[str, Any]]:
    specs: list[dict[str, Any]] = []
    for capability_id in gap_capabilities:
        component_ids = tuple(
            sorted(
                component_id
                for component_id in component_by_capability.get(capability_id, set())
                if components.get(component_id, {}).get("implementation_state") != "VALIDATED"
            )
        )
        if component_ids:
            for component_id in component_ids:
                specs.append(
                    _implementation_task_spec(
                        compilation,
                        resolution,
                        trace,
                        capabilities[capability_id],
                        components[component_id],
                        requirements_by_capability,
                        trace_path_by_requirement,
                    )
                )
        else:
            specs.append(
                _implementation_task_spec(
                    compilation,
                    resolution,
                    trace,
                    capabilities[capability_id],
                    None,
                    requirements_by_capability,
                    trace_path_by_requirement,
                )
            )
    return sorted(specs, key=lambda item: str(item["id"]))


def _implementation_task_spec(
    compilation: CompilationResult,
    resolution: CapabilityResolution,
    trace: TraceValidationResult,
    capability: ResolvedCapability,
    component: dict[str, Any] | None,
    requirements_by_capability: dict[str, set[str]],
    trace_path_by_requirement: dict[str, TracePath],
) -> dict[str, Any]:
    capability_id = capability.capability_id
    component_id = str(component["id"]) if component else None
    task_id = f"IMPL-{capability_id}-{component_id}" if component_id else f"IMPL-{capability_id}-CONTRACT"
    requirements = tuple(sorted(requirements_by_capability.get(capability_id, set())))
    interfaces = tuple(
        sorted(
            interface_id
            for requirement_id in requirements
            for interface_id in trace_path_by_requirement.get(requirement_id, TracePath(requirement_id, "INVALID", (), (), (), (), ())).interfaces
        )
    )
    components = (component_id,) if component_id else ()
    title_target = str(component.get("name")) if component else f"{capability_id} {capability.name} contract"
    task_material = {
        "id": task_id,
        "capability": capability_id,
        "component": component_id,
        "requirements": requirements,
        "interfaces": interfaces,
        "source_compiled_hash": compilation.lock.compiled_hash,
        "capability_resolution_hash": resolution.capability_resolution_hash,
        "trace_validation_hash": trace.trace_validation_hash,
        "generator_version": IMPLEMENTATION_DAG_GENERATOR_VERSION,
    }
    return {
        "id": task_id,
        "title": f"Implement {title_target}",
        "objective": _task_objective(capability, component),
        "implements": {
            "requirements": requirements,
            "capabilities": (capability_id,),
            "components": components,
            "interfaces": interfaces,
        },
        "write_scope": {
            "allowed": _allowed_paths_for(capability_id, component_id),
            "prohibited": (".env", ".env.*", "aient/**", ".bootstrap/**", ".build/**"),
        },
        "execution": {
            "agent_role": _agent_role_for(capability_id),
            "model_profile": _model_profile_for(capability_id),
            "executor": "codex",
        },
        "verification": {
            "profile": _verification_profile_for(capability_id),
            "acceptance_criteria": _acceptance_criteria(capability, component, requirements),
        },
        "risk": {"level": _risk_level_for(capability_id), "reason": _risk_reason_for(capability_id)},
        "provenance": {
            "compiled_project_hash": compilation.lock.compiled_hash,
            "capability_resolution_hash": resolution.capability_resolution_hash,
            "trace_validation_hash": trace.trace_validation_hash,
            "generator_version": IMPLEMENTATION_DAG_GENERATOR_VERSION,
        },
        "fingerprint": hashlib.sha256(canonical_bytes(task_material)).hexdigest(),
        "epic_id": _epic_for(capability_id),
        "feature_id": _feature_for(capability_id),
        "component_id": component_id,
    }


def _task_from_spec(spec: dict[str, Any]) -> GeneratedImplementationTask:
    return GeneratedImplementationTask(
        id=str(spec["id"]),
        title=str(spec["title"]),
        objective=str(spec["objective"]),
        implements={
            "requirements": tuple(spec["implements"]["requirements"]),
            "capabilities": tuple(spec["implements"]["capabilities"]),
            "components": tuple(spec["implements"]["components"]),
            "interfaces": tuple(spec["implements"]["interfaces"]),
        },
        depends_on=(),
        write_scope={
            "allowed": tuple(spec["write_scope"]["allowed"]),
            "prohibited": tuple(spec["write_scope"]["prohibited"]),
        },
        execution=dict(spec["execution"]),
        verification=dict(spec["verification"]),
        risk=dict(spec["risk"]),
        provenance=dict(spec["provenance"]),
        fingerprint=str(spec["fingerprint"]),
        epic_id=str(spec["epic_id"]),
        feature_id=str(spec["feature_id"]),
        component_id=spec["component_id"],
    )


def _replace_task_dependencies(
    task: GeneratedImplementationTask,
    depends_on: tuple[str, ...],
) -> GeneratedImplementationTask:
    return GeneratedImplementationTask(
        id=task.id,
        title=task.title,
        objective=task.objective,
        implements=task.implements,
        depends_on=depends_on,
        write_scope=task.write_scope,
        execution=task.execution,
        verification=task.verification,
        risk=task.risk,
        provenance=task.provenance,
        fingerprint=task.fingerprint,
        epic_id=task.epic_id,
        feature_id=task.feature_id,
        component_id=task.component_id,
    )


def _implementation_dependency_edges(
    tasks: tuple[GeneratedImplementationTask, ...],
    resolution: CapabilityResolution,
) -> tuple[tuple[str, str], ...]:
    tasks_by_capability: dict[str, list[str]] = {}
    task_by_component: dict[str, str] = {}
    for task in tasks:
        for capability_id in task.implements["capabilities"]:
            tasks_by_capability.setdefault(capability_id, []).append(task.id)
        if task.component_id:
            task_by_component[task.component_id] = task.id
    capability_dependencies = {
        capability.capability_id: capability.direct_dependencies
        for capability in resolution.capabilities
    }
    edges: set[tuple[str, str]] = set()
    for task in tasks:
        capability_id = task.implements["capabilities"][0]
        for dependency_capability in capability_dependencies.get(capability_id, ()):
            for dependency_task_id in tasks_by_capability.get(dependency_capability, []):
                if dependency_task_id != task.id:
                    edges.add((task.id, dependency_task_id))
    component_sequence = ["CMP-001", "CMP-002", "CMP-003", "CMP-004", "CMP-005", "CMP-006", "CMP-007"]
    for before, after in pairwise(component_sequence):
        before_task = task_by_component.get(before)
        after_task = task_by_component.get(after)
        if before_task and after_task and before_task != after_task:
            edges.add((after_task, before_task))
    return tuple(sorted(edges))


def _validate_implementation_plan(
    tasks: tuple[GeneratedImplementationTask, ...],
    dependency_edges: tuple[tuple[str, str], ...],
    gap_capabilities: tuple[str, ...],
) -> tuple[ImplementationPlanFinding, ...]:
    findings: list[ImplementationPlanFinding] = []
    task_ids = {task.id for task in tasks}
    covered_capabilities = {capability_id for task in tasks for capability_id in task.implements["capabilities"]}
    duplicate_task_ids = sorted({task.id for task in tasks if [candidate.id for candidate in tasks].count(task.id) > 1})
    for task_id in duplicate_task_ids:
        findings.append(ImplementationPlanFinding(f"PLAN-{task_id}-DUPLICATE", "ERROR", task_id, "duplicate generated task id"))
    for task_id, dependency_id in dependency_edges:
        if task_id == dependency_id:
            findings.append(ImplementationPlanFinding(f"PLAN-{task_id}-SELF-DEPENDENCY", "ERROR", task_id, "task depends on itself"))
        if task_id not in task_ids:
            findings.append(ImplementationPlanFinding(f"PLAN-{task_id}-MISSING", "ERROR", task_id, "dependency edge references missing task"))
        if dependency_id not in task_ids:
            findings.append(
                ImplementationPlanFinding(f"PLAN-{task_id}-{dependency_id}-MISSING-DEPENDENCY", "ERROR", task_id, "dependency edge references omitted task")
            )
    for capability_id in gap_capabilities:
        if capability_id not in covered_capabilities:
            findings.append(
                ImplementationPlanFinding(
                    f"PLAN-{capability_id}-UNCOVERED",
                    "ERROR",
                    capability_id,
                    "implementation gap has no generated task",
                )
            )
    for task in tasks:
        if not task.implements["requirements"] and not task.implements["capabilities"] and not task.implements["components"]:
            findings.append(ImplementationPlanFinding(f"PLAN-{task.id}-ORPHAN", "ERROR", task.id, "generated task has no justification"))
        if not task.verification["acceptance_criteria"]:
            findings.append(ImplementationPlanFinding(f"PLAN-{task.id}-NO-VERIFY", "ERROR", task.id, "generated task has no acceptance criteria"))
        if len(task.implements["capabilities"]) > 2 or len(task.write_scope["allowed"]) > 4:
            findings.append(ImplementationPlanFinding(f"PLAN-{task.id}-BROAD-SCOPE", "WARNING", task.id, "generated task scope should be reviewed"))
    cycle = _task_cycle({task.id: set(task.depends_on) for task in tasks})
    if cycle:
        findings.append(ImplementationPlanFinding("PLAN-CYCLE", "ERROR", "implementation-dag", f"task dependency cycle: {' -> '.join(cycle)}"))
    return tuple(sorted(findings, key=lambda item: item.finding_id))


def _implementation_waves(
    tasks: tuple[GeneratedImplementationTask, ...],
    dependency_edges: tuple[tuple[str, str], ...],
) -> list[dict[str, Any]]:
    remaining = {task.id for task in tasks}
    dependencies = {task.id: {dependency for task_id, dependency in dependency_edges if task_id == task.id} for task in tasks}
    completed: set[str] = set()
    waves: list[dict[str, Any]] = []
    while remaining:
        ready = sorted(task_id for task_id in remaining if dependencies.get(task_id, set()).issubset(completed))
        if not ready:
            raise ValueError("generated implementation DAG contains a cycle")
        waves.append({"id": f"WAVE-{len(waves) + 1:03d}", "task_ids": ready})
        completed.update(ready)
        remaining.difference_update(ready)
    return waves


def _parallelizable_sets(
    tasks: tuple[GeneratedImplementationTask, ...],
    waves: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    by_id = {task.id: task for task in tasks}
    sets: list[dict[str, Any]] = []
    for wave in waves:
        compatible: list[str] = []
        used_scopes: set[str] = set()
        for task_id in wave["task_ids"]:
            scopes = set(by_id[task_id].write_scope["allowed"])
            if not used_scopes.intersection(scopes):
                compatible.append(task_id)
                used_scopes.update(scopes)
        sets.append({"wave_id": wave["id"], "task_ids": compatible})
    return sets


def _critical_path(
    tasks: tuple[GeneratedImplementationTask, ...],
    dependency_edges: tuple[tuple[str, str], ...],
) -> tuple[str, ...]:
    dependencies = {task.id: tuple(sorted(dependency for task_id, dependency in dependency_edges if task_id == task.id)) for task in tasks}
    memo: dict[str, tuple[str, ...]] = {}

    def path_to(task_id: str) -> tuple[str, ...]:
        if task_id in memo:
            return memo[task_id]
        candidates = [path_to(dependency) for dependency in dependencies.get(task_id, ())]
        prefix = max(candidates, key=lambda path: (len(path), path), default=())
        memo[task_id] = (*prefix, task_id)
        return memo[task_id]

    paths = [path_to(task.id) for task in tasks]
    return max(paths, key=lambda path: (len(path), path), default=())


def _human_gates(tasks: tuple[GeneratedImplementationTask, ...]) -> list[dict[str, Any]]:
    gates = []
    for task in tasks:
        if task.risk["level"] in {"HIGH", "HUMAN_REVIEW"}:
            gates.append(
                {
                    "id": f"GATE-{task.id}",
                    "task_id": task.id,
                    "reason": task.risk["reason"],
                    "required_before": "execution",
                }
            )
    return sorted(gates, key=lambda item: item["id"])


def _classify_trace_warnings(findings: tuple[TraceFinding, ...]) -> tuple[ClassifiedTraceWarning, ...]:
    warnings = []
    for finding in findings:
        if finding.severity != "WARNING":
            continue
        classification: WarningClassification = "PLANNING_RELEVANT" if finding.finding_id.endswith("-GAP") else "INFORMATIONAL"
        if "FUTURE" in finding.message.upper() or "deferred" in finding.message.lower():
            classification = "REQUIRES_FUTURE_DECISION"
        warnings.append(ClassifiedTraceWarning(finding.finding_id, finding.subject_id, classification, finding.message))
    return tuple(sorted(warnings, key=lambda item: item.finding_id))


def _task_cycle(dependencies: dict[str, set[str]]) -> list[str]:
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(task_id: str, path: list[str]) -> list[str]:
        if task_id in visiting:
            return path[path.index(task_id):]
        if task_id in visited:
            return []
        visiting.add(task_id)
        for dependency in sorted(dependencies.get(task_id, set())):
            cycle = visit(dependency, [*path, dependency])
            if cycle:
                return cycle
        visiting.remove(task_id)
        visited.add(task_id)
        return []

    for task_id in sorted(dependencies):
        cycle = visit(task_id, [task_id])
        if cycle:
            return cycle
    return []


def _task_objective(capability: ResolvedCapability, component: dict[str, Any] | None) -> str:
    if component:
        return (
            f"Implement the missing {component['name']} behavior needed for {capability.capability_id} "
            f"without replacing already validated bootstrap-engine functionality."
        )
    return (
        f"Define and implement the missing bounded contract for {capability.capability_id} {capability.name} "
        "so later dependent implementation units have an explicit service boundary."
    )


def _allowed_paths_for(capability_id: str, component_id: str | None) -> tuple[str, ...]:
    if component_id in {"CMP-001", "CMP-002", "CMP-003", "CMP-004"} or capability_id in {"C01", "C02", "C14", "C15", "C16", "C17"}:
        return ("src/ai_ent/**", "tests/**", "scripts/**", "manifest/project/ai-ent/**")
    return ("src/ai_ent/**", "tests/**", "scripts/**")


def _agent_role_for(capability_id: str) -> str:
    if capability_id == "C17":
        return "AGT-002"
    if capability_id == "C18":
        return "AGT-003"
    if capability_id in {"C03", "C20"}:
        return "AGT-004"
    return "AGT-001"


def _model_profile_for(capability_id: str) -> str:
    if capability_id in {"C02", "C04", "C16", "C20"}:
        return "ARCHITECTURE_REASONING"
    if capability_id in {"C03", "C06", "C14"}:
        return "SECURITY_REVIEW"
    return "CODING_STANDARD"


def _verification_profile_for(capability_id: str) -> str:
    if capability_id in {"C03", "C20"}:
        return "FULL_REGRESSION"
    return "STANDARD_REGRESSION"


def _acceptance_criteria(
    capability: ResolvedCapability,
    component: dict[str, Any] | None,
    requirements: tuple[str, ...],
) -> tuple[str, ...]:
    target = str(component["id"]) if component else capability.capability_id
    return (
        f"{target} behavior is implemented behind the established AI-Enterprise service boundaries.",
        f"Requirements {', '.join(requirements) or 'for the capability contract'} are covered by deterministic tests.",
        "Existing bootstrap-engine, compiler, scheduler, verifier, and Git safety regressions remain passing.",
    )


def _risk_level_for(capability_id: str) -> str:
    if capability_id in {"C04", "C14", "C18", "C20"}:
        return "HIGH"
    if capability_id in {"C03", "C16", "C17", "C19"}:
        return "MEDIUM"
    return "LOW"


def _risk_reason_for(capability_id: str) -> str:
    if capability_id == "C14":
        return "identity or tenant behavior requires human review"
    if capability_id in {"C04", "C18"}:
        return "AI agent orchestration changes require bounded autonomy review"
    if capability_id == "C20":
        return "runtime kernel and evidence graph changes affect orchestration safety"
    if capability_id in {"C03", "C16", "C17", "C19"}:
        return "core compiler/runtime behavior requires focused regression"
    return "internal deterministic implementation"


def _epic_for(capability_id: str) -> str:
    if capability_id in {"C01", "C02", "C03", "C14"}:
        return "EPC-001"
    if capability_id in {"C15", "C16"}:
        return "EPC-002"
    if capability_id in {"C17", "C18"}:
        return "EPC-003"
    return "EPC-004"


def _feature_for(capability_id: str) -> str:
    if capability_id in {"C01", "C02", "C03", "C14"}:
        return "FEA-001"
    if capability_id in {"C15", "C16"}:
        return "FEA-002"
    return "FEA-003"


def _validate_capability_graph_inputs(capabilities: dict[str, dict[str, Any]]) -> None:
    expected = {f"C{number:02d}" for number in range(1, 21)}
    actual = set(capabilities)
    if actual != expected:
        raise ValueError(f"capability IDs must be C01-C20: missing={sorted(expected - actual)} extra={sorted(actual - expected)}")
    for capability_id, capability in capabilities.items():
        for conflict in capability.get("conflicts_with", []):
            if conflict not in capabilities:
                raise ValueError(f"{capability_id} conflicts_with unknown capability {conflict}")
            if conflict == capability_id:
                raise ValueError(f"{capability_id} cannot conflict with itself")


def _condition_matches(compiled: dict[str, Any], condition: object) -> bool:
    if not isinstance(condition, dict):
        return False
    path = condition.get("path")
    if not isinstance(path, str):
        return False
    value = _path_value(compiled, path)
    if "equals" in condition:
        return value == condition["equals"]
    if "not_equals" in condition:
        return value != condition["not_equals"]
    return False


def _path_value(value: Any, dotted_path: str) -> Any:
    current = value
    for part in dotted_path.split("."):
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def _capability_cycle(dependencies: dict[str, set[str]]) -> list[str]:
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(capability_id: str, path: list[str]) -> list[str]:
        if capability_id in visiting:
            return path[path.index(capability_id):]
        if capability_id in visited:
            return []
        visiting.add(capability_id)
        for dependency in sorted(dependencies.get(capability_id, set())):
            cycle = visit(dependency, [*path, dependency])
            if cycle:
                return cycle
        visiting.remove(capability_id)
        visited.add(capability_id)
        return []

    for capability_id in sorted(dependencies):
        cycle = visit(capability_id, [capability_id])
        if cycle:
            return cycle
    return []


def _transitive_dependencies(capability_id: str, dependencies: dict[str, set[str]]) -> set[str]:
    result: set[str] = set()

    def visit(current: str) -> None:
        for dependency in sorted(dependencies.get(current, set())):
            if dependency not in result:
                result.add(dependency)
                visit(dependency)

    visit(capability_id)
    return result


def _required_capability_set(
    capabilities: dict[str, dict[str, Any]],
    direct_dependencies: dict[str, set[str]],
) -> set[str]:
    required = {capability_id for capability_id, capability in capabilities.items() if capability.get("status") == "REQUIRED"}
    expanded = set(required)
    for capability_id in sorted(required):
        expanded.update(_transitive_dependencies(capability_id, direct_dependencies))
        expanded.update(direct_dependencies.get(capability_id, set()))
    return expanded


def _resolve_capability(
    capability: dict[str, Any],
    direct_dependencies: set[str],
    transitive_dependencies: tuple[str, ...],
    applied_conditionals: list[dict[str, Any]],
    required: set[str],
) -> ResolvedCapability:
    capability_id = str(capability["id"])
    declared_status = capability["status"]
    resolved_status: ResolvedCapabilityStatus = "REQUIRED" if capability_id in required else declared_status
    maturity = capability["maturity"]
    evidence_refs = tuple(sorted(str(item) for item in capability.get("evidence_refs", [])))
    satisfaction = _satisfaction(resolved_status, maturity, evidence_refs)
    blockers = tuple(
        sorted(
            [
                f"missing implementation evidence for {capability_id}"
                for _ in [capability_id]
                if satisfaction == "UNSATISFIED"
            ]
        )
    )
    return ResolvedCapability(
        capability_id=capability_id,
        name=str(capability["name"]),
        declared_status=declared_status,
        resolved_status=resolved_status,
        maturity=maturity,
        satisfaction=satisfaction,
        direct_dependencies=tuple(sorted(direct_dependencies)),
        transitive_dependencies=transitive_dependencies,
        conditional_dependencies_applied=tuple(applied_conditionals),
        evidence_refs=evidence_refs,
        missing_requirements_components=tuple(_missing_requirements_components(capability_id, satisfaction)),
        blockers=blockers,
        source_provenance=tuple(sorted(str(item) for item in capability.get("source_refs", []))),
    )


def _satisfaction(status: str, maturity: str, evidence_refs: tuple[str, ...]) -> CapabilitySatisfaction:
    if status in {"DEFERRED", "NOT_REQUIRED"}:
        return "DEFERRED" if status == "DEFERRED" else "NOT_APPLICABLE"
    if status == "CONDITIONAL" and maturity == "NOT_IMPLEMENTED":
        return "NOT_APPLICABLE"
    if maturity in {"VALIDATED", "PRODUCTION_READY"}:
        return "SATISFIED"
    if maturity == "DEVELOPMENT":
        return "PARTIALLY_SATISFIED"
    if evidence_refs:
        return "PARTIALLY_SATISFIED"
    return "UNSATISFIED"


def _missing_requirements_components(capability_id: str, satisfaction: CapabilitySatisfaction) -> list[str]:
    if satisfaction in {"SATISFIED", "NOT_APPLICABLE", "DEFERRED"}:
        return []
    return [f"{capability_id}:implementation"]


def _parse_project(documents: dict[Path, dict[str, Any]], errors: list[str]) -> ProjectDocument | None:
    project_path = next((path for path in documents if path.name == "project.yaml"), None)
    if project_path is None:
        errors.append("missing project.yaml")
        return None
    try:
        return ProjectDocument.model_validate(documents[project_path])
    except ValidationError as exc:
        errors.append(f"project.yaml schema error: {_compact_validation(exc)}")
        return None


def _parse_capabilities(documents: dict[Path, dict[str, Any]], errors: list[str]) -> list[Capability]:
    path = next((candidate for candidate in documents if candidate.name == "capabilities.yaml"), None)
    if path is None:
        errors.append("missing capabilities.yaml")
        return []
    raw = documents[path].get("capabilities", [])
    if not isinstance(raw, list):
        errors.append("capabilities.yaml capabilities must be a list")
        return []
    capabilities: list[Capability] = []
    for item in raw:
        try:
            capabilities.append(Capability.model_validate(item))
        except ValidationError as exc:
            errors.append(f"capability schema error: {_compact_validation(exc)}")
    if len(capabilities) != 20:
        errors.append(f"expected 20 capabilities, found {len(capabilities)}")
    return capabilities


def _items(documents: dict[Path, dict[str, Any]], key: str) -> list[TraceableItem]:
    items: list[TraceableItem] = []
    for document in documents.values():
        raw = document.get(key)
        if isinstance(raw, list):
            for value in raw:
                if isinstance(value, dict) and "id" in value:
                    items.append(TraceableItem.model_validate(value))
    return items


def _validate_unique_ids(documents: dict[Path, dict[str, Any]], errors: list[str]) -> None:
    seen: dict[str, Path] = {}
    for path, document in documents.items():
        for item_id in _walk_ids(document):
            previous = seen.get(item_id)
            if previous is not None:
                errors.append(f"duplicate id {item_id}: {previous} and {path}")
            else:
                seen[item_id] = path


def _walk_ids(value: object) -> list[str]:
    ids: list[str] = []
    if isinstance(value, dict):
        item_id = value.get("id")
        if isinstance(item_id, str):
            ids.append(item_id)
        for child in value.values():
            ids.extend(_walk_ids(child))
    elif isinstance(value, list):
        for child in value:
            ids.extend(_walk_ids(child))
    return ids


def _validate_source_refs(documents: dict[Path, dict[str, Any]], source_ids: set[str], errors: list[str]) -> None:
    for path, document in documents.items():
        for source_ref in _walk_source_refs(document):
            if source_ref not in source_ids:
                errors.append(f"unresolved source_ref {source_ref}: {path}")


def _walk_source_refs(value: object) -> list[str]:
    refs: list[str] = []
    if isinstance(value, dict):
        raw = value.get("source_refs")
        if isinstance(raw, list):
            refs.extend(str(item) for item in raw)
        for child in value.values():
            refs.extend(_walk_source_refs(child))
    elif isinstance(value, list):
        for child in value:
            refs.extend(_walk_source_refs(child))
    return refs


def _validate_capability_dependencies(capabilities: list[Capability], capability_ids: set[str], errors: list[str]) -> None:
    for capability in capabilities:
        for dependency in capability.depends_on:
            if dependency not in capability_ids:
                errors.append(f"{capability.id} depends on unknown capability {dependency}")


def _validate_capability_refs(item: TraceableItem, capability_ids: set[str], errors: list[str]) -> None:
    refs = [*item.capabilities]
    if item.capability:
        refs.append(item.capability)
    for capability_id in refs:
        if capability_id not in capability_ids:
            errors.append(f"{item.id} references unknown capability {capability_id}")


def _validate_interfaces(items: list[TraceableItem], component_ids: set[str], errors: list[str]) -> None:
    for item in items:
        if item.from_component not in component_ids:
            errors.append(f"{item.id} references unknown from_component {item.from_component}")
        if item.to_component not in component_ids:
            errors.append(f"{item.id} references unknown to_component {item.to_component}")


def _validate_feature_refs(
    features: list[TraceableItem],
    epic_ids: set[str],
    requirement_ids: set[str],
    errors: list[str],
) -> None:
    for feature in features:
        epic = getattr(feature, "epic", None)
        if isinstance(epic, str) and epic not in epic_ids:
            errors.append(f"{feature.id} references unknown epic {epic}")
        for requirement_id in feature.requirements:
            if requirement_id not in requirement_ids:
                errors.append(f"{feature.id} references unknown requirement {requirement_id}")


def _item_id(item: TraceableItem) -> str:
    return item.id


def _unresolved_decisions(documents: dict[Path, dict[str, Any]]) -> list[str]:
    unresolved: list[str] = []
    for document in documents.values():
        decisions = document.get("decisions")
        if isinstance(decisions, list):
            for decision in decisions:
                if isinstance(decision, dict) and decision.get("status") in {"open", "unresolved"}:
                    unresolved.append(str(decision.get("id", "unknown")))
    return sorted(unresolved)


def _compact_validation(exc: ValidationError) -> str:
    first = exc.errors()[0]
    loc = ".".join(str(part) for part in first.get("loc", ()))
    message = str(first.get("msg", "validation failed"))
    return f"{loc}: {message}" if loc else message
