from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, ValidationError

Classification = Literal["NORMATIVE", "INFORMATIVE", "DECISION", "EXAMPLE", "FUTURE/DEFERRED"]
CapabilityStatus = Literal["REQUIRED", "CONDITIONAL", "DEFERRED", "NOT_REQUIRED"]
CapabilityMaturity = Literal["NOT_IMPLEMENTED", "DEVELOPMENT", "VALIDATED", "PRODUCTION_READY"]

PROJECT_MANIFEST_ROOT = Path("manifest/project/ai-ent")
PROJECT_MANIFEST_SCHEMA_VERSION = "ai-ent-project-manifest-v0.1"
PROJECT_MANIFEST_COMPILER_VERSION = "mmc-002.1"
GENERATED_MARKER = "generated by ai_ent.project_manifest; source manifests remain authoritative"


class SourceRef(BaseModel):
    id: str
    path: str
    role: str


class ProjectDocument(BaseModel):
    id: str
    name: str
    version: str
    classification: Classification
    status: str
    source_corpus: list[SourceRef] = Field(default_factory=list)
    objectives: list[str] = Field(default_factory=list)
    already_implemented_platform_capabilities: list[str] = Field(default_factory=list)
    authority: dict[str, Any] = Field(default_factory=dict)


class Capability(BaseModel):
    id: str
    name: str
    status: CapabilityStatus
    maturity: CapabilityMaturity
    classification: Classification
    source_refs: list[str]
    depends_on: list[str] = Field(default_factory=list)


class TraceableItem(BaseModel):
    id: str
    title: str | None = None
    name: str | None = None
    classification: Classification | None = None
    source_refs: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    capability: str | None = None
    requirements: list[str] = Field(default_factory=list)
    epic: str | None = None
    depends_on: list[str] = Field(default_factory=list)
    from_component: str | None = None
    to_component: str | None = None


@dataclass(frozen=True)
class ManifestValidationResult:
    manifest_files: tuple[str, ...]
    requirements_count: int
    components_count: int
    interfaces_count: int
    capabilities_selected: tuple[str, ...]
    unresolved_decisions: tuple[str, ...]
    validation_errors: tuple[str, ...]
    validation_warnings: tuple[str, ...]
    already_satisfied: tuple[str, ...]
    still_missing: tuple[str, ...]
    compilation_hash: str

    @property
    def ok(self) -> bool:
        return not self.validation_errors

    def as_dict(self) -> dict[str, Any]:
        return {
            "manifest_files_loaded": list(self.manifest_files),
            "requirements_count": self.requirements_count,
            "components_count": self.components_count,
            "interfaces_count": self.interfaces_count,
            "capabilities_selected": list(self.capabilities_selected),
            "unresolved_decisions": list(self.unresolved_decisions),
            "validation_errors": list(self.validation_errors),
            "validation_warnings": list(self.validation_warnings),
            "implementation_areas_already_satisfied": list(self.already_satisfied),
            "implementation_areas_still_missing": list(self.still_missing),
            "compilation_hash": self.compilation_hash,
        }


@dataclass(frozen=True)
class CompiledProject:
    project: dict[str, Any]
    intake: dict[str, Any]
    requirements: tuple[dict[str, Any], ...]
    architecture: dict[str, Any]
    capabilities: tuple[dict[str, Any], ...]
    agents: tuple[dict[str, Any], ...]
    models: tuple[dict[str, Any], ...]
    tools: tuple[dict[str, Any], ...]
    verification: dict[str, Any]
    repository: dict[str, Any]
    deployment: dict[str, Any]
    operations: tuple[dict[str, Any], ...]
    planning: dict[str, Any]
    source_metadata: dict[str, Any]

    def as_dict(self) -> dict[str, Any]:
        return {
            "compiler_version": PROJECT_MANIFEST_COMPILER_VERSION,
            "manifest_schema_version": PROJECT_MANIFEST_SCHEMA_VERSION,
            "generated": GENERATED_MARKER,
            "source_authority": "manifest/project/ai-ent",
            "project": self.project,
            "intake": self.intake,
            "requirements": list(self.requirements),
            "architecture": self.architecture,
            "capabilities": list(self.capabilities),
            "agents": list(self.agents),
            "models": list(self.models),
            "tools": list(self.tools),
            "verification": self.verification,
            "repository": self.repository,
            "deployment": self.deployment,
            "operations": list(self.operations),
            "planning": self.planning,
            "source_metadata": self.source_metadata,
        }


@dataclass(frozen=True)
class ManifestLock:
    project_id: str
    manifest_schema_version: str
    compiler_version: str
    source_file_hashes: dict[str, str]
    source_compilation_hash: str
    compiled_hash: str
    generated: str = GENERATED_MARKER

    def as_dict(self) -> dict[str, Any]:
        return {
            "generated": self.generated,
            "project_id": self.project_id,
            "manifest_schema_version": self.manifest_schema_version,
            "compiler_version": self.compiler_version,
            "source_file_hashes": self.source_file_hashes,
            "source_compilation_hash": self.source_compilation_hash,
            "compiled_hash": self.compiled_hash,
        }


@dataclass(frozen=True)
class CompilationResult:
    compiled: CompiledProject
    lock: ManifestLock
    compiled_bytes: bytes
    validation: ManifestValidationResult


def validate_project_manifest(root: Path = PROJECT_MANIFEST_ROOT) -> ManifestValidationResult:
    documents = load_manifest_documents(root)
    errors: list[str] = []
    warnings: list[str] = []

    project = _parse_project(documents, errors)
    source_ids = {source.id for source in project.source_corpus} if project else set()
    source_ids.add("BEAG-001")

    capabilities = _parse_capabilities(documents, errors)
    capability_ids = {capability.id for capability in capabilities}
    _validate_unique_ids(documents, errors)
    _validate_source_refs(documents, source_ids, errors)
    _validate_capability_dependencies(capabilities, capability_ids, errors)

    requirements = _items(documents, "requirements")
    components = _items(documents, "components")
    interfaces = _items(documents, "interfaces")
    agents = _items(documents, "agents")
    epics = _items(documents, "epics")
    features = _items(documents, "features")

    for item in [*requirements, *components, *agents]:
        _validate_capability_refs(item, capability_ids, errors)
    component_ids = {_item_id(component) for component in components}
    requirement_ids = {_item_id(requirement) for requirement in requirements}
    epic_ids = {_item_id(epic) for epic in epics}
    _validate_interfaces(interfaces, component_ids, errors)
    _validate_feature_refs(features, epic_ids, requirement_ids, errors)

    selected = tuple(sorted(capability.id for capability in capabilities if capability.status in {"REQUIRED", "CONDITIONAL"}))
    already = tuple(sorted(capability.id for capability in capabilities if capability.maturity in {"VALIDATED", "PRODUCTION_READY"}))
    missing = tuple(
        sorted(
            capability.id
            for capability in capabilities
            if capability.status == "REQUIRED" and capability.maturity not in {"VALIDATED", "PRODUCTION_READY"}
        )
    )
    unresolved = _unresolved_decisions(documents)
    if not unresolved:
        warnings.append("no unresolved decisions recorded")

    return ManifestValidationResult(
        manifest_files=tuple(sorted(str(path.relative_to(root)) for path in documents)),
        requirements_count=len(requirements),
        components_count=len(components),
        interfaces_count=len(interfaces),
        capabilities_selected=selected,
        unresolved_decisions=tuple(unresolved),
        validation_errors=tuple(errors),
        validation_warnings=tuple(warnings),
        already_satisfied=already,
        still_missing=missing,
        compilation_hash=compilation_hash(documents),
    )


def load_manifest_documents(root: Path) -> dict[Path, dict[str, Any]]:
    if not root.exists():
        raise FileNotFoundError(f"project manifest root not found: {root}")
    documents: dict[Path, dict[str, Any]] = {}
    for path in sorted(root.rglob("*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(loaded, dict):
            raise TypeError(f"{path} must contain a YAML mapping")
        documents[path] = loaded
    return documents


def compile_project_manifest(root: Path = PROJECT_MANIFEST_ROOT) -> CompilationResult:
    validation = validate_project_manifest(root)
    if not validation.ok:
        raise ValueError("project manifest validation failed: " + "; ".join(validation.validation_errors))
    documents = load_manifest_documents(root)
    compiled = _compile_documents(root, documents)
    compiled_bytes = canonical_bytes(compiled.as_dict())
    compiled_hash = hashlib.sha256(compiled_bytes).hexdigest()
    lock = ManifestLock(
        project_id=str(compiled.project["id"]),
        manifest_schema_version=PROJECT_MANIFEST_SCHEMA_VERSION,
        compiler_version=PROJECT_MANIFEST_COMPILER_VERSION,
        source_file_hashes=_source_file_hashes(root, documents),
        source_compilation_hash=validation.compilation_hash,
        compiled_hash=compiled_hash,
    )
    return CompilationResult(
        compiled=compiled,
        lock=lock,
        compiled_bytes=compiled_bytes,
        validation=validation,
    )


def write_compiled_project(root: Path = PROJECT_MANIFEST_ROOT, output_dir: Path = Path(".build/compiled")) -> CompilationResult:
    result = compile_project_manifest(root)
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "project.json", result.compiled.as_dict())
    _write_json(output_dir / "manifest.lock", result.lock.as_dict())
    _write_json(output_dir / "requirements.json", {"requirements": list(result.compiled.requirements)})
    _write_json(output_dir / "architecture.json", result.compiled.architecture)
    _write_json(output_dir / "capabilities.json", {"capabilities": list(result.compiled.capabilities)})
    _write_json(output_dir / "planning.json", result.compiled.planning)
    return result


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(_normalize(value), sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")


def compilation_hash(documents: dict[Path, dict[str, Any]]) -> str:
    normalized = {
        str(path): documents[path]
        for path in sorted(documents, key=lambda item: str(item))
    }
    payload = json.dumps(normalized, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _compile_documents(root: Path, documents: dict[Path, dict[str, Any]]) -> CompiledProject:
    project_path = root / "project.yaml"
    project_document = documents[project_path]
    project = _with_source(_normalize(project_document), root, project_path)
    intake_path = root / "intake.yaml"
    intake = _with_source(_normalize(documents[intake_path]), root, intake_path)
    capabilities_path = root / "capabilities.yaml"
    capabilities = tuple(
        _with_source(item, root, capabilities_path)
        for item in _sort_by_id(_normalize(_document_named(documents, "capabilities.yaml")).get("capabilities", []))
    )
    requirements = tuple(
        _with_source(requirement, root, path)
        for path in sorted(documents)
        for requirement in _sort_by_id(_normalize(documents[path]).get("requirements", []))
    )
    agents = _merged_items(root, documents, "agents", include_paths=("agents.yaml",))
    models = _merged_items(root, documents, "models")
    tools = _merged_items(root, documents, "tools")
    operations = _merged_items(root, documents, "operations")
    architecture = {
        "components": list(_merged_items(root, documents, "components")),
        "interfaces": list(_merged_items(root, documents, "interfaces")),
        "data_objects": list(_merged_items(root, documents, "data_objects")),
        "agent_topology": _normalize(_document_by_relative_path(root, documents, "architecture/agent-topology.yaml").get("agents", [])),
        "deployment": _normalize(_document_by_relative_path(root, documents, "architecture/deployment.yaml").get("deployment", {})),
        "security_controls": list(_merged_items(root, documents, "security_controls")),
        "system_flow": _normalize(_document_by_relative_path(root, documents, "architecture/system.yaml").get("flow", [])),
    }
    planning = {
        "roadmap": _normalize(_document_by_relative_path(root, documents, "planning/roadmap.yaml").get("roadmap", [])),
        "epics": _normalize(_document_by_relative_path(root, documents, "planning/epics.yaml").get("epics", [])),
        "features": _normalize(_document_by_relative_path(root, documents, "planning/features.yaml").get("features", [])),
        "task_graph": _normalize(_document_by_relative_path(root, documents, "planning/task-graph.yaml").get("task_graph", {})),
        "implementation_waves": _normalize(
            _document_by_relative_path(root, documents, "planning/implementation-waves.yaml").get("implementation_waves", [])
        ),
    }
    return CompiledProject(
        project=project,
        intake=intake,
        requirements=requirements,
        architecture=_normalize(architecture),
        capabilities=capabilities,
        agents=agents,
        models=models,
        tools=tools,
        verification=_with_source(_normalize(_document_named(documents, "verification.yaml")), root, _path_named(documents, "verification.yaml")),
        repository=_with_source(_normalize(documents[root / "repository.yaml"]), root, root / "repository.yaml"),
        deployment=_with_source(_normalize(documents[root / "deployment.yaml"]), root, root / "deployment.yaml"),
        operations=operations,
        planning=_normalize(planning),
        source_metadata={
            "source_files": sorted(str(path.relative_to(root)) for path in documents),
            "source_file_count": len(documents),
            "source_file_hashes": _source_file_hashes(root, documents),
        },
    )


def _normalize(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            str(key): _normalize(value[key])
            for key in sorted(value)
            if value[key] is not None
        }
    if isinstance(value, list):
        normalized = [_normalize(item) for item in value]
        if all(isinstance(item, str) for item in normalized):
            return sorted(normalized)
        return normalized
    if isinstance(value, str):
        return value.strip()
    return value


def _sort_by_id(items: Any) -> list[dict[str, Any]]:
    if not isinstance(items, list):
        return []
    mappings = [item for item in items if isinstance(item, dict)]
    return sorted(mappings, key=lambda item: str(item.get("id", "")))


def _merged_items(
    root: Path,
    documents: dict[Path, dict[str, Any]],
    key: str,
    *,
    include_paths: tuple[str, ...] | None = None,
) -> tuple[dict[str, Any], ...]:
    items: list[dict[str, Any]] = []
    for path in sorted(documents):
        if include_paths is not None and str(path.relative_to(root)) not in include_paths:
            continue
        raw = _normalize(documents[path]).get(key)
        if isinstance(raw, list):
            items.extend(_with_source(item, root, path) for item in _sort_by_id(raw))
    return tuple(sorted(items, key=lambda item: str(item.get("id", ""))))


def _with_source(item: dict[str, Any], root: Path, path: Path) -> dict[str, Any]:
    enriched = dict(item)
    enriched["source_manifest_file"] = str(path.relative_to(root))
    return enriched


def _document_named(documents: dict[Path, dict[str, Any]], name: str) -> dict[str, Any]:
    return documents[_path_named(documents, name)]


def _path_named(documents: dict[Path, dict[str, Any]], name: str) -> Path:
    matches = [path for path in documents if path.name == name]
    if len(matches) != 1:
        raise ValueError(f"expected exactly one {name}, found {len(matches)}")
    return matches[0]


def _document_by_relative_path(root: Path, documents: dict[Path, dict[str, Any]], relative_path: str) -> dict[str, Any]:
    path = root / relative_path
    return documents[path]


def _source_file_hashes(root: Path, documents: dict[Path, dict[str, Any]]) -> dict[str, str]:
    return {
        str(path.relative_to(root)): hashlib.sha256(canonical_bytes(documents[path])).hexdigest()
        for path in sorted(documents)
    }


def _write_json(path: Path, value: Any) -> None:
    path.write_bytes(canonical_bytes(value) + b"\n")


def _parse_project(documents: dict[Path, dict[str, Any]], errors: list[str]) -> ProjectDocument | None:
    project_path = next((path for path in documents if path.name == "project.yaml"), None)
    if project_path is None:
        errors.append("missing project.yaml")
        return None
    try:
        return ProjectDocument.model_validate(documents[project_path])
    except ValidationError as exc:
        errors.append(f"project.yaml schema error: {_compact_validation(exc)}")
        return None


def _parse_capabilities(documents: dict[Path, dict[str, Any]], errors: list[str]) -> list[Capability]:
    path = next((candidate for candidate in documents if candidate.name == "capabilities.yaml"), None)
    if path is None:
        errors.append("missing capabilities.yaml")
        return []
    raw = documents[path].get("capabilities", [])
    if not isinstance(raw, list):
        errors.append("capabilities.yaml capabilities must be a list")
        return []
    capabilities: list[Capability] = []
    for item in raw:
        try:
            capabilities.append(Capability.model_validate(item))
        except ValidationError as exc:
            errors.append(f"capability schema error: {_compact_validation(exc)}")
    if len(capabilities) != 20:
        errors.append(f"expected 20 capabilities, found {len(capabilities)}")
    return capabilities


def _items(documents: dict[Path, dict[str, Any]], key: str) -> list[TraceableItem]:
    items: list[TraceableItem] = []
    for document in documents.values():
        raw = document.get(key)
        if isinstance(raw, list):
            for value in raw:
                if isinstance(value, dict) and "id" in value:
                    items.append(TraceableItem.model_validate(value))
    return items


def _validate_unique_ids(documents: dict[Path, dict[str, Any]], errors: list[str]) -> None:
    seen: dict[str, Path] = {}
    for path, document in documents.items():
        for item_id in _walk_ids(document):
            previous = seen.get(item_id)
            if previous is not None:
                errors.append(f"duplicate id {item_id}: {previous} and {path}")
            else:
                seen[item_id] = path


def _walk_ids(value: object) -> list[str]:
    ids: list[str] = []
    if isinstance(value, dict):
        item_id = value.get("id")
        if isinstance(item_id, str):
            ids.append(item_id)
        for child in value.values():
            ids.extend(_walk_ids(child))
    elif isinstance(value, list):
        for child in value:
            ids.extend(_walk_ids(child))
    return ids


def _validate_source_refs(documents: dict[Path, dict[str, Any]], source_ids: set[str], errors: list[str]) -> None:
    for path, document in documents.items():
        for source_ref in _walk_source_refs(document):
            if source_ref not in source_ids:
                errors.append(f"unresolved source_ref {source_ref}: {path}")


def _walk_source_refs(value: object) -> list[str]:
    refs: list[str] = []
    if isinstance(value, dict):
        raw = value.get("source_refs")
        if isinstance(raw, list):
            refs.extend(str(item) for item in raw)
        for child in value.values():
            refs.extend(_walk_source_refs(child))
    elif isinstance(value, list):
        for child in value:
            refs.extend(_walk_source_refs(child))
    return refs


def _validate_capability_dependencies(capabilities: list[Capability], capability_ids: set[str], errors: list[str]) -> None:
    for capability in capabilities:
        for dependency in capability.depends_on:
            if dependency not in capability_ids:
                errors.append(f"{capability.id} depends on unknown capability {dependency}")


def _validate_capability_refs(item: TraceableItem, capability_ids: set[str], errors: list[str]) -> None:
    refs = [*item.capabilities]
    if item.capability:
        refs.append(item.capability)
    for capability_id in refs:
        if capability_id not in capability_ids:
            errors.append(f"{item.id} references unknown capability {capability_id}")


def _validate_interfaces(items: list[TraceableItem], component_ids: set[str], errors: list[str]) -> None:
    for item in items:
        if item.from_component not in component_ids:
            errors.append(f"{item.id} references unknown from_component {item.from_component}")
        if item.to_component not in component_ids:
            errors.append(f"{item.id} references unknown to_component {item.to_component}")


def _validate_feature_refs(
    features: list[TraceableItem],
    epic_ids: set[str],
    requirement_ids: set[str],
    errors: list[str],
) -> None:
    for feature in features:
        epic = getattr(feature, "epic", None)
        if isinstance(epic, str) and epic not in epic_ids:
            errors.append(f"{feature.id} references unknown epic {epic}")
        for requirement_id in feature.requirements:
            if requirement_id not in requirement_ids:
                errors.append(f"{feature.id} references unknown requirement {requirement_id}")


def _item_id(item: TraceableItem) -> str:
    return item.id


def _unresolved_decisions(documents: dict[Path, dict[str, Any]]) -> list[str]:
    unresolved: list[str] = []
    for document in documents.values():
        decisions = document.get("decisions")
        if isinstance(decisions, list):
            for decision in decisions:
                if isinstance(decision, dict) and decision.get("status") in {"open", "unresolved"}:
                    unresolved.append(str(decision.get("id", "unknown")))
    return sorted(unresolved)


def _compact_validation(exc: ValidationError) -> str:
    first = exc.errors()[0]
    loc = ".".join(str(part) for part in first.get("loc", ()))
    message = str(first.get("msg", "validation failed"))
    return f"{loc}: {message}" if loc else message
